// Every picture the games show: the English Wikipedia page whose lead image it is, or a File: on Commons. Settings'
// "Keep pictures offline" downloads them all (pics.js), so the paintings, buildings and places show with no connection.
// Written by tools/build-kb.mjs from kb/: edit kb/, not this file.
export const PICTURES = [
"30 St Mary Axe",
"550 Madison Avenue",
"A Bigger Splash",
"A Burial at Ornans",
"A Sunday Afternoon on the Island of La Grande Jatte",
"A Thousand Li of Rivers and Mountains",
"Acropolis Museum",
"Adoration of the Magi (Gentile da Fabriano)",
"Albertina",
"Alhambra",
"Along the River During the Qingming Festival",
"Amalienburg",
"American Gothic",
"American Museum of Natural History",
"Among the Sierra Nevada, California",
"Anne Frank House",
"Annunciation with Saint Margaret and Saint Ansanus",
"Apartheid Museum",
"Arnolfini Portrait",
"Art Gallery of New South Wales",
"Art Gallery of Ontario",
"Ashmolean Museum",
"At the Moulin Rouge",
"Ateneum",
"Auschwitz-Birkenau State Museum",
"Automatic watch",
"BMW Museum",
"Bacchus (Caravaggio)",
"Bacchus and Ariadne",
"Bal du moulin de la Galette",
"Balance spring",
"Balance wheel",
"Barbican Estate",
"Barcelona Pavilion",
"Barge Haulers on the Volga",
"Bargello",
"Barnes Foundation",
"Bauhaus Dessau",
"Beijing National Stadium",
"Black Square",
"Blenheim Palace",
"Blue Horse I",
"Brandenburg Gate",
"Broadway Boogie Woogie",
"Burj Khalifa",
"Café Terrace at Night",
"Calouste Gulbenkian Museum",
"Campbell's Soup Cans",
"Capitoline Museums",
"Cartier Tank",
"Casa Batlló",
"Centre Pompidou",
"Chalk Cliffs on Rügen",
"Charles I at the Hunt",
"Chartres Cathedral",
"Chichu Art Museum",
"Chiswick House",
"Christina's World",
"Chronograph",
"Chrysler Building",
"Cité des Sciences et de l'Industrie",
"Cleveland Museum of Art",
"Cologne Cathedral",
"Colosseum",
"Composition VII",
"Composition VIII",
"Composition with Red, Blue and Yellow",
"Computer History Museum",
"Dalí Theatre and Museum",
"Dance (Matisse)",
"Death and the Maiden (Schiele)",
"Detroit Institute of Arts",
"Deutsches Historisches Museum",
"Deutsches Museum",
"Doni Tondo",
"Drowning Girl",
"Durham Cathedral",
"Dynamism of a Dog on a Leash",
"Early Spring (painting)",
"Early Sunday Morning",
"Egyptian Museum",
"Elbphilharmonie",
"Empire State Building",
"Et in Arcadia ego (Poussin)",
"Exploratorium",
"Fallingwater",
"Field Museum of Natural History",
"File:Alexey Bogolybov - Port of Tallinn (1853).jpg",
"File:Kirchner - Mountain Landscape from Clavadel.jpg",
"File:View of Canton factories 2.jpg",
"Fine Wind, Clear Morning",
"Fitzwilliam Museum",
"Florence Cathedral",
"Fondation Louis Vuitton",
"Forbidden City",
"Fram Museum",
"Frans Hals Museum",
"French National Museum of Natural History",
"Frida Kahlo Museum",
"Fundació Joan Miró",
"Fusee (horology)",
"Galleria Borghese",
"Gallerie dell'Accademia",
"Gemäldegalerie Alte Meister",
"Ghent Altarpiece",
"Girl with a Pearl Earring",
"Glasgow School of Art",
"Golconda (Magritte)",
"Gold Museum, Bogotá",
"Grand Central Terminal",
"Grand Egyptian Museum",
"Grande Odalisque",
"Green Vault",
"Groeningemuseum",
"Guernica (Picasso)",
"Guggenheim Museum Bilbao",
"Guilloché",
"HSBC Main Building",
"Hagia Sophia",
"Henry Ford Museum of American Innovation",
"Hiroshima Peace Memorial Museum",
"Hylas and the Nymphs (painting)",
"Hôtel Tassel",
"Imperial War Museum",
"Impression, Sunrise",
"Isabella Stewart Gardner Museum",
"Isenheim Altarpiece",
"Isle of the Dead (painting)",
"Israel Museum",
"Istanbul Archaeology Museums",
"Ivan the Terrible and His Son Ivan",
"Jaeger-LeCoultre Reverso",
"Jewish Museum Berlin",
"Judith Beheading Holofernes (Caravaggio)",
"Judith Slaying Holofernes (Artemisia Gentileschi, Florence)",
"Kennedy Space Center Visitor Complex",
"Kimbell Art Museum",
"Kon-Tiki Museum",
"Kremlin Armoury",
"L'Absinthe",
"Lady with an Ermine",
"Lamentation (The Mourning of Christ)",
"Lamentation of Christ (Mantegna)",
"Larco Museum",
"Las Meninas",
"Le Déjeuner sur l'herbe",
"Le bonheur de vivre",
"Leopold Museum",
"Les Demoiselles d'Avignon",
"Lever escapement",
"Liberty Leading the People",
"Lloyd's building",
"Louisiana Museum of Modern Art",
"Louvre Abu Dhabi",
"Louvre Pyramid",
"Luncheon of the Boating Party",
"M+",
"Madonna with the Long Neck",
"Maestà (Duccio)",
"Mainspring",
"Marilyn Diptych",
"Marine chronometer",
"Marriage A-la-Mode (Hogarth)",
"Mary Rose",
"Massacre of the Innocents (Rubens)",
"Mercedes-Benz Museum",
"Milan Cathedral",
"Minute repeater",
"Mona Lisa",
"Monticello",
"Morning in a Pine Forest",
"Mosque–Cathedral of Córdoba",
"Mr and Mrs Andrews",
"Museo Egizio",
"Museo Ferrari",
"Museo Galileo",
"Museo Nacional de Bellas Artes (Buenos Aires)",
"Museo Soumaya",
"Museu Nacional d'Art de Catalunya",
"Museum Ludwig",
"Museum für Naturkunde",
"Museum of Anthropology at UBC",
"Museum of Fine Arts (Budapest)",
"Museum of Islamic Art, Doha",
"Museum of New Zealand Te Papa Tongarewa",
"Museum of Old and New Art",
"Museum of Science and Industry (Chicago)",
"Musée Picasso",
"Musée Rodin",
"Musée de Cluny",
"Musée de l'Armée",
"Musée des Arts et Métiers",
"Musée du quai Branly – Jacques Chirac",
"Napoleon Crossing the Alps",
"National Air and Space Museum",
"National Archaeological Museum, Athens",
"National Archaeological Museum, Naples",
"National Gallery Singapore",
"National Gallery of Art",
"National Gallery of Canada",
"National Gallery of Ireland",
"National Gallery of Victoria",
"National Maritime Museum",
"National Museum of African American History and Culture",
"National Museum of American History",
"National Museum of Anthropology (Mexico)",
"National Museum of Capodimonte",
"National Museum of China",
"National Museum of Korea",
"National Museum of Natural History",
"National Museum of Nature and Science",
"National Museum of Scotland",
"National Museum of Western Art",
"National Portrait Gallery, London",
"National Railway Museum",
"National September 11 Memorial & Museum",
"Nationalmuseum",
"Natural History Museum, London",
"Natural History Museum, Vienna",
"Netherlandish Proverbs",
"Neues Museum",
"Neuschwanstein Castle",
"Nighthawks",
"No. 5, 1948",
"No. 61 (Rust and Blue)",
"Nobel Prize Museum",
"Notre-Dame de Paris",
"Nude Descending a Staircase, No. 2",
"Number 1, 1950 (Lavender Mist)",
"Nuremberg Chronicle",
"Oath of the Horatii",
"Olympia (Manet)",
"Omega Speedmaster",
"Ophelia (painting)",
"Palace of Versailles",
"Palace of Westminster",
"Palais Garnier",
"Palazzo Pitti",
"Pantheon, Rome",
"Paris Street; Rainy Day",
"Parthenon",
"Peggy Guggenheim Collection",
"Pinacoteca di Brera",
"Pinakothek der Moderne",
"Pitt Rivers Museum",
"Plum Park in Kameido",
"Pont du Gard",
"Porsche Museum",
"Portinari Altarpiece",
"Portland Building",
"Portrait of Adele Bloch-Bauer I",
"Portrait of Georg Giese",
"Portrait of Innocent X",
"Portrait of Madame X",
"Portrait of Madame de Pompadour",
"Primavera (Botticelli)",
"Proserpine (Rossetti)",
"Pushkin Museum",
"Rain, Steam and Speed – The Great Western Railway",
"Rembrandt House Museum",
"Rokeby Venus",
"Rolex Daytona",
"Rolex Submariner",
"Royal Museum of Fine Arts Antwerp",
"Royal Ontario Museum",
"Royal Tyrrell Museum of Palaeontology",
"Rubenshuis",
"Sagrada Família",
"Sainte-Chapelle",
"Salvator Mundi (Leonardo)",
"San Carlo alle Quattro Fontane",
"San Francisco Museum of Modern Art",
"Sanssouci",
"Saturn Devouring His Son",
"Science Museum, London",
"Scottish National Gallery",
"Seagram Building",
"Secession Building",
"Self-Portrait (Dürer, Munich)",
"Self-Portrait in a Convex Mirror (Parmigianino)",
"Self-Portrait with Bandaged Ear",
"Self-Portrait with Thorn Necklace and Hummingbird",
"Shaanxi History Museum",
"Shanghai Museum",
"Sistine Madonna",
"Solomon R. Guggenheim Museum",
"Speyer Cathedral",
"St Paul's Cathedral",
"St. Peter's Basilica",
"St. Peter's Square",
"Stedelijk Museum Amsterdam",
"Städel",
"Sudden Shower over Shin-Ōhashi bridge and Atake",
"Sunflowers (Van Gogh series)",
"Swiss Museum of Transport",
"Sydney Opera House",
"Syndics of the Drapers' Guild",
"São Paulo Museum of Art",
"Taj Mahal",
"Temple of Heaven",
"Terracotta Army",
"The Ambassadors (Holbein)",
"The Anatomy Lesson of Dr. Nicolaes Tulp",
"The Angelus (painting)",
"The Art of Painting",
"The Ballet Class (Degas, Musée d'Orsay)",
"The Baptism of Christ (Piero della Francesca)",
"The Battle of Alexander at Issus",
"The Battle of San Romano",
"The Birth of Venus",
"The Blue Boy",
"The Boating Party",
"The Bookworm (Spitzweg)",
"The Burial of the Count of Orgaz",
"The Burning Giraffe",
"The Calling of Saint Matthew",
"The Card Players",
"The Chocolate Girl",
"The City Rises",
"The Coronation of Napoleon",
"The Courtyard of a House in Delft",
"The Creation of Adam",
"The Death of Marat",
"The Death of Sardanapalus",
"The Descent from the Cross (van der Weyden)",
"The Elephant Celebes",
"The Elevation of the Cross (Rubens)",
"The Embarkation for Cythera",
"The Embarkation of the Queen of Sheba",
"The Feast of Saint Nicholas",
"The Fighting Temeraire",
"The Four Apostles",
"The Frick Collection",
"The Garden of Earthly Delights",
"The Gleaners",
"The Goldfinch (painting)",
"The Great Wave off Kanagawa",
"The Gross Clinic",
"The Gulf Stream (painting)",
"The Harlequin's Carnival",
"The Hay Wain",
"The Heart of the Andes",
"The Hunters in the Snow",
"The Iron Rolling Mill (Modern Cyclopes)",
"The Jewish Bride",
"The Kiss (Klimt)",
"The Lacemaker (Vermeer)",
"The Lady of Shalott (painting)",
"The Last Judgment (Memling)",
"The Last Supper (Leonardo)",
"The Laughing Cavalier",
"The Little Street",
"The Milkmaid (Vermeer)",
"The Miraculous Draft of Fishes (Witz)",
"The Monarch of the Glen (painting)",
"The Money Changer and His Wife",
"The Night Watch",
"The Nightmare",
"The Ninth Wave",
"The Oxbow",
"The Peasant Wedding",
"The Persistence of Memory",
"The Poor Poet",
"The Raft of the Medusa",
"The School of Athens",
"The Scream",
"The Sea of Ice",
"The Slave Ship",
"The Sleeping Gypsy",
"The Son of Man (Magritte)",
"The Starry Night",
"The Stonemason's Yard",
"The Storm on the Sea of Galilee",
"The Surrender of Breda",
"The Swing (Fragonard)",
"The Tempest (Giorgione)",
"The Third of May 1808",
"The Tower of Babel (Bruegel)",
"The Treachery of Images",
"The Two Fridas",
"The Weeping Woman",
"Therme Vals",
"Three Musicians (Picasso)",
"Thyssen-Bornemisza Museum",
"Tokyo National Museum",
"Topkapı Palace",
"Tourbillon",
"Travelers Among Mountains and Streams",
"Two Men Contemplating the Moon",
"Ulm Minster",
"United States Capitol",
"United States Holocaust Memorial Museum",
"Unité d'habitation (Marseille)",
"Unterlinden Museum",
"Vasa Museum",
"Venus of Urbino",
"Venus, Cupid, Folly and Time",
"Vertumnus (Arcimboldo)",
"Victoria and Albert Museum",
"View of Delft",
"View of Toledo",
"Villa La Rotonda",
"Villa Savoye",
"Vir Heroicus Sublimis",
"Virgin of the Rocks",
"Vitra Fire Station",
"Wainwright Building",
"Walhalla memorial",
"Walk on the Beach",
"Walt Disney Concert Hall",
"Wanderer above the Sea of Fog",
"Washington Crossing the Delaware (1851 paintings)",
"Water Lilies (Monet series)",
"Westminster Abbey",
"Whaam!",
"Wheatfield with Crows",
"Where Do We Come From? What Are We? Where Are We Going?",
"Whistler's Mother",
"White on White",
"Whitney Museum",
"Wieskirche",
"Windmill at Wijk bij Duurstede",
"Woman I",
"Woman with a Hat",
"Woman with a Parasol – Madame Monet and Her Son",
"Würzburg Residence",
"Yad Vashem",
"Zeitz Museum of Contemporary Art Africa"
];
