// Refinery's campaign: one unit at a time, each level a crude, a set of units and a lesson. Par comes from the
// engine's solver when the level loads.
export const LEVELS = [
  { id: 1, title: "Hydroskimming", crude: "bonny", units: ["cdu", "nht", "reformer", "kht", "dht", "sru"],
    lesson: "The simplest refinery: distil, treat, reform. Every cut has a pool it belongs in, once it's been treated.",
    intro: "Bonny Light is sweet and full of distillate. Send the heavy naphtha through the hydrotreater to the reformer, the kerosene to the kerosene treater, the gas oils to the diesel hydrotreater, and see what the pools make. The residue has nowhere to go but fuel oil." },
  { id: 2, title: "The vacuum unit and the FCC", crude: "brent", units: ["cdu", "vdu", "fcc", "cnht", "nht", "reformer", "kht", "dht", "sru"],
    lesson: "Residue is worth more cut apart: vacuum gas oil to the cracker, which makes gasoline, LPG and propylene, and leaves cycle oil and slurry.",
    intro: "Brent's residue is a third of the barrel. The vacuum unit lifts the gas oil out of it for the FCC. FCC naphtha is sour: it needs its post-treater before the gasoline pool. Decide where the cycle oil goes." },
  { id: 3, title: "Sulphur", crude: "urals", units: ["cdu", "vdu", "fcc", "cnht", "nht", "reformer", "kht", "dht", "sru"],
    lesson: "A sour crude puts sulphur in every cut. Untreated streams poison a pool: one wrong stream and the whole pool sells as fuel oil.",
    intro: "Urals carries 1.6% sulphur. Watch the diesel pool's sulphur and cetane: light cycle oil treats to 10 ppm but its cetane of 25 can still sink the pool. Sometimes the right place for LCO is fuel oil." },
  { id: 4, title: "Octane", crude: "wti", units: ["cdu", "vdu", "fcc", "cnht", "nht", "reformer", "isom", "kht", "dht", "sru"],
    lesson: "Gasoline is a blend: reformate brings the octane, isomerate lifts the light naphtha, FCC naphtha fills the pool.",
    intro: "WTI is naphtha-rich. Light naphtha at RON 70 drags the pool under 95; the isomerisation unit takes it to 88. The reformer's hydrogen now runs the hydrotreaters." },
  { id: 5, title: "The hydrocracker", crude: "arabHeavy", units: ["cdu", "vdu", "fcc", "hcu", "smr", "cnht", "nht", "reformer", "isom", "kht", "dht", "sru"],
    lesson: "Where the FCC makes gasoline, the hydrocracker makes jet and diesel, swelling the barrel, at a cost in hydrogen that the hydrogen plant has to supply.",
    intro: "Arab Heavy is half residue. Split the vacuum gas oil between the FCC and the hydrocracker: the light VGO suits the hydrocracker, the heavy the FCC, and the prices decide the rest. Hydrocracker naphtha is clean but low in octane: the reformer takes it." },
  { id: 6, title: "Alkylation", crude: "wti", units: ["cdu", "vdu", "fcc", "cnht", "alky", "nht", "reformer", "isom", "kht", "dht", "sru"],
    lesson: "The FCC's C4 olefins are worth LPG money, or alkylate money: octane 95 with no sulphur and no aromatics.",
    intro: "Route the FCC's C4s to the alkylation unit instead of the LPG pool and watch the gasoline pool's octane and volume." },
  { id: 7, title: "The coker", crude: "maya", units: ["cdu", "vdu", "fcc", "hcu", "smr", "coker", "visbreaker", "bitumen", "cnht", "alky", "nht", "reformer", "isom", "kht", "dht", "sru"],
    lesson: "The bottom of the barrel: coke it, visbreak it, blow it to bitumen, or sell it as fuel oil. Everything the coker makes is sour and olefinic and needs treating.",
    intro: "Maya is 60% residue and cheap for it. The coker turns vacuum residue into naphtha, gas oil and coke; the gas oil wants the hydrocracker or the FCC, the naphtha wants the hydrotreater before the reformer. Compare with bitumen and with the visbreaker." },
  { id: 8, title: "Renewables", crude: "brent", units: ["cdu", "vdu", "fcc", "hcu", "smr", "cnht", "alky", "nht", "reformer", "isom", "kht", "dht", "sru", "hvoUnit"], renewables: { vegOil: 8, ethanol: 4, fame: 3 },
    lesson: "Your territory: HVO is diesel chemistry on a vegetable feed, hydrogen-hungry, paid with a ticket; ethanol brings octane; FAME blends in up to 7%.",
    intro: "Eight thousand barrels a day of vegetable oil and used cooking oil, four of ethanol, three of FAME. The HVO unit needs 3,000 scf of hydrogen a barrel. Decide where the HVO goes: into the diesel pool, where it lifts cetane, or sold on its own with its ticket value." },
  { id: 9, title: "Full complexity", crude: "arabHeavy", units: ["cdu", "vdu", "fcc", "hcu", "smr", "coker", "visbreaker", "bitumen", "cnht", "alky", "nht", "reformer", "isom", "kht", "dht", "sru", "hvoUnit"], renewables: { vegOil: 5, ethanol: 4, fame: 3 }, chooseCrude: true,
    lesson: "Every unit, every stream, and the crude is yours to choose. The configuration decides which crude pays.",
    intro: "A full-conversion refinery. Pick the crude from the menu and route everything. Heavy sour crudes are cheap because only a refinery like this one can turn them into clean products." },
];
