// Refinery: the units, the streams between them, the products and the crudes. Yields are typical textbook
// figures in volume per cent of feed (hydrocrackers swell; cokers lose to gas and coke), properties are typical
// values for blending, prices are a plausible 2024-ish deck in $/bbl. Everything is simplified to what matters
// for routing: what a unit eats, what it makes, what it costs, and what it needs.

// ---------- streams ----------
// ron: research octane; cet: cetane; s: sulphur in ppm; jet: can go to the jet pool as is; group: where it sits
export const STREAMS = {
  gas: { name: "Fuel gas", short: "Gas", group: "gas", note: "Methane and ethane. Burned in the refinery's own furnaces." },
  lpg: { name: "LPG", short: "LPG", group: "gas", note: "Propane and butane. Sold as bottled gas or petrochemical feed." },
  propylene: { name: "Propylene", short: "C3=", group: "gas", note: "An olefin from the FCC, prized by petrochemicals for polypropylene." },
  c4: { name: "FCC C4s", short: "C4s", group: "gas", note: "Butenes and isobutane from the FCC: the feed for alkylation." },
  lsr: { name: "Light naphtha", short: "LSR", group: "naphtha", ron: 70, s: 200, note: "C5–C6 straight-run naphtha. Low octane; isomerisation lifts it." },
  hsr: { name: "Heavy naphtha", short: "HSR", group: "naphtha", ron: 55, s: 400, note: "C7–C10 straight-run naphtha: reformer feed, after hydrotreating." },
  hsrT: { name: "Treated heavy naphtha", short: "HSR (HT)", group: "naphtha", ron: 55, s: 1, note: "Heavy naphtha with its sulphur removed, as the reformer's catalyst demands." },
  reformate: { name: "Reformate", short: "Ref.", group: "naphtha", ron: 100, s: 1, note: "Aromatic, high-octane gasoline blendstock, and the reformer's hydrogen comes with it." },
  isomerate: { name: "Isomerate", short: "Isom.", group: "naphtha", ron: 88, s: 1, note: "Branched C5–C6: light naphtha with its octane lifted." },
  catNaphtha: { name: "FCC naphtha", short: "Cat naph.", group: "naphtha", ron: 92, s: 600, note: "Olefinic cracked gasoline from the FCC: good octane, but sulphur that has to come out." },
  catNaphthaT: { name: "Treated FCC naphtha", short: "Cat naph. (HT)", group: "naphtha", ron: 90, s: 10, note: "FCC naphtha after its post-treater, at a small octane cost." },
  alkylate: { name: "Alkylate", short: "Alky.", group: "naphtha", ron: 95, s: 1, note: "The cleanest gasoline blendstock: high octane, low vapour pressure, no aromatics." },
  cokerNaphtha: { name: "Coker naphtha", short: "Coker naph.", group: "naphtha", ron: 65, s: 3000, note: "Olefinic, sour naphtha from the coker; hydrotreating first, then the reformer." },
  hcNaphtha: { name: "Hydrocracker naphtha", short: "HC naph.", group: "naphtha", ron: 65, s: 1, note: "Clean, low-octane naphtha from the hydrocracker: reformer feed." },
  kero: { name: "Kerosene", short: "Kero", group: "middle", cet: 42, s: 1500, note: "The straight-run kerosene cut. Jet fuel once its sulphur and mercaptans are dealt with." },
  jet: { name: "Jet fuel", short: "Jet", group: "middle", cet: 42, s: 10, jet: true, note: "Kerosene that meets the jet specification." },
  lgo: { name: "Light gas oil", short: "LGO", group: "middle", cet: 53, s: 8000, note: "Straight-run diesel, sour until hydrotreated." },
  hgo: { name: "Heavy gas oil", short: "HGO", group: "middle", cet: 49, s: 12000, note: "The heaviest atmospheric cut: diesel after treating, or cracker feed." },
  lco: { name: "Light cycle oil", short: "LCO", group: "middle", cet: 25, s: 9000, note: "Aromatic cracked gas oil from the FCC: poor cetane, drags the diesel pool down." },
  ulsd: { name: "Hydrotreated diesel", short: "ULSD", group: "middle", cet: 50, s: 8, note: "Gas oil with its sulphur taken to 10 ppm." },
  hcJet: { name: "Hydrocracker jet", short: "HC jet", group: "middle", cet: 45, s: 5, jet: true, note: "Clean kerosene from the hydrocracker: straight to the jet pool." },
  hcDiesel: { name: "Hydrocracker diesel", short: "HC diesel", group: "middle", cet: 56, s: 5, note: "High-cetane, ultra-low-sulphur diesel: the hydrocracker's best product." },
  cokerGo: { name: "Coker gas oil", short: "Coker GO", group: "middle", cet: 38, s: 20000, note: "Sour, olefinic gas oil from the coker: cracker feed after treating, or diesel at a cost." },
  hvo: { name: "HVO", short: "HVO", group: "middle", cet: 75, s: 1, note: "Renewable diesel: hydrotreated vegetable oil or waste fat. Paraffinic, superb cetane, sold with its ticket value." },
  lvgo: { name: "Light vacuum gas oil", short: "LVGO", group: "heavy", s: 15000, note: "The lighter vacuum gas oil: cracker feed, or heavy diesel after a hard hydrotreat." },
  hvgo: { name: "Heavy vacuum gas oil", short: "HVGO", group: "heavy", s: 22000, note: "The heavy vacuum gas oil: the main feed for the FCC or the hydrocracker." },
  bitumen: { name: "Bitumen", short: "Bitumen", group: "resid", note: "Road bitumen, blown from asphaltic vacuum residue." },
  slurry: { name: "Slurry oil", short: "Slurry", group: "heavy", s: 20000, note: "Decant oil from the bottom of the FCC: fuel-oil blendstock or carbon black feed." },
  atmResid: { name: "Atmospheric residue", short: "Atm. resid", group: "resid", s: 25000, note: "What's left after atmospheric distillation: vacuum unit feed, or fuel oil." },
  vacResid: { name: "Vacuum residue", short: "Vac. resid", group: "resid", s: 35000, note: "The bottom of the barrel: coker, visbreaker, bitumen, or fuel oil." },
  visResid: { name: "Visbroken residue", short: "Visb. resid", group: "resid", s: 35000, note: "Residue thinned by the visbreaker so it blends to fuel oil with less cutter." },
  fuelOilCutter: { name: "Visbreaker gas oil", short: "Visb. GO", group: "middle", cet: 35, s: 15000, note: "A little gas oil cracked out by the visbreaker." },
  coke: { name: "Petroleum coke", short: "Coke", group: "resid", note: "Solid carbon from the coker, sold for cement kilns and anodes." },
  vegOil: { name: "Vegetable oil / UCO", short: "Veg. oil", group: "renewable", note: "Rapeseed, palm or used cooking oil: the feed for an HVO unit." },
  fame: { name: "FAME", short: "FAME", group: "renewable", cet: 54, s: 5, note: "Biodiesel from transesterification. Blends into diesel up to 7% under EN 590." },
  ethanol: { name: "Ethanol", short: "EtOH", group: "renewable", ron: 108, s: 0, note: "Fermentation ethanol: up to 10% in E10 gasoline." },
  h2: { name: "Hydrogen", short: "H2", group: "other", note: "Made by the reformer and the hydrogen plant; eaten by every hydrotreater and the hydrocracker." },
  h2s: { name: "Hydrogen sulphide", short: "H2S", group: "other", note: "The sulphur stripped out by hydrotreating, as a gas, bound for the sulphur plant." },
  sulphur: { name: "Sulphur", short: "S", group: "other", note: "Elemental sulphur from the Claus plant: sold for sulphuric acid." },
};

// ---------- units ----------
// feeds: streams the unit accepts; yields: outputs as a fraction of feed volume (by feed where it matters);
// h2: thousand scf of hydrogen per barrel of feed, negative when consumed; opex: $/bbl of feed
export const UNITS = {
  cdu: { name: "Crude distillation unit", short: "CDU", kind: "distillation", feeds: [], opex: 1,
    purpose: "Boils crude and takes it apart by boiling range: gases off the top, naphtha, kerosene, gas oils, and the atmospheric residue off the bottom.",
    card: ["The first unit every barrel sees. A furnace heats the crude to about 350–370 °C and a tall column separates it into cuts by boiling point.",
      "The yields are the crude's own: a light sweet crude gives a lot of naphtha and distillate, a heavy sour one mostly residue.",
      "Nothing is converted here, only sorted. Everything downstream exists to upgrade what comes out."] },
  vdu: { name: "Vacuum distillation unit", short: "VDU", kind: "distillation", feeds: ["atmResid"], opex: 0.7,
    yields: { atmResid: { lvgo: null, hvgo: null, vacResid: null } },         // by crude: see CRUDES.vgoShare (40% light, 60% heavy)
    purpose: "Distils the atmospheric residue under vacuum, where it boils without cracking, into vacuum gas oil and vacuum residue.",
    card: ["Residue would crack and coke if heated further at atmospheric pressure, so the vacuum column boils it at a tenth of an atmosphere.",
      "Vacuum gas oil is the prize: the feed for the FCC or the hydrocracker, where the money is made.",
      "What's left, the vacuum residue, is the bottom of the barrel: coker, visbreaker, bitumen or fuel oil."] },
  nht: { name: "Naphtha hydrotreater", short: "NHT", kind: "treating", feeds: ["hsr", "cokerNaphtha", "hcNaphtha"], opex: 0.7, carry: { ron: 0, s: 1 },
    yields: { hsr: { hsrT: 0.99, gas: 0.01 }, cokerNaphtha: { hsrT: 0.97, gas: 0.03 }, hcNaphtha: { hsrT: 1 } },
    h2: { hsr: -0.1, cokerNaphtha: -0.5, hcNaphtha: 0 },
    purpose: "Strips sulphur and nitrogen out of naphtha, over a catalyst with hydrogen, to protect the reformer's platinum.",
    card: ["The reformer's catalyst is poisoned by a few ppm of sulphur, so naphtha is hydrotreated first.",
      "Straight-run naphtha needs little hydrogen; coker naphtha, olefinic and sour, needs five times as much.",
      "The sulphur leaves as hydrogen sulphide, bound for the sulphur plant."] },
  reformer: { name: "Catalytic reformer", short: "CCR", kind: "octane", feeds: ["hsrT"], opex: 2.5,
    yields: { hsrT: { reformate: 0.83, lpg: 0.07, gas: 0.05 } },
    h2: { hsrT: 1.0 },
    purpose: "Rearranges heavy naphtha into aromatics over platinum, lifting octane from the 50s to 100, and makes hydrogen doing it.",
    card: ["Dehydrogenation and cyclisation turn paraffins into aromatics: octane goes from about 55 to 100.",
      "The reactions release hydrogen, about 1,000 scf a barrel: the reformer is the refinery's own hydrogen supply.",
      "Continuous catalyst regeneration (CCR) keeps the platinum fresh, so modern units run at high severity all year."] },
  isom: { name: "Isomerisation unit", short: "Isom", kind: "octane", feeds: ["lsr"], opex: 1.2,
    yields: { lsr: { isomerate: 0.98, gas: 0.02 } },
    h2: { lsr: -0.05 },
    purpose: "Converts straight-chain C5 and C6 paraffins into their branched isomers, lifting light naphtha's octane from 70 to the high 80s.",
    card: ["Light naphtha is too light to reform and too low in octane to blend as it is.",
      "Over a chlorided platinum or zeolite catalyst with a little hydrogen, normal pentane and hexane become their branched isomers.",
      "Octane rises from about 70 to 88 with almost no loss of volume."] },
  fcc: { name: "Fluid catalytic cracker", short: "FCC", kind: "conversion", feeds: ["lvgo", "hvgo", "hgo", "cokerGo"], opex: 3,
    yields: { lvgo: { gas: 0.04, propylene: 0.05, c4: 0.09, lpg: 0.03, catNaphtha: 0.5, lco: 0.16, slurry: 0.06 },
      hvgo: { gas: 0.04, propylene: 0.05, c4: 0.09, lpg: 0.03, catNaphtha: 0.48, lco: 0.18, slurry: 0.08 },
      hgo: { gas: 0.04, propylene: 0.05, c4: 0.09, lpg: 0.03, catNaphtha: 0.46, lco: 0.2, slurry: 0.07 },
      cokerGo: { gas: 0.05, propylene: 0.04, c4: 0.08, lpg: 0.03, catNaphtha: 0.42, lco: 0.22, slurry: 0.1 } },
    h2: {},
    purpose: "Cracks vacuum gas oil over a hot fluidised zeolite catalyst into gasoline, LPG and olefins; the coke that forms is burned off to drive the unit.",
    card: ["The workhorse of a gasoline refinery. Hot catalyst meets the feed in a riser for a couple of seconds, cracking it to lighter molecules.",
      "About half the feed becomes high-octane but sour naphtha; a fifth is light cycle oil, which has terrible cetane; the rest is LPG, propylene and slurry.",
      "Coke deposits on the catalyst and is burned off in the regenerator, which heats the catalyst for the next pass: the unit needs no external fuel."] },
  hcu: { name: "Hydrocracker", short: "HCU", kind: "conversion", feeds: ["lvgo", "hvgo", "cokerGo"], opex: 5,
    yields: { lvgo: { lpg: 0.06, hcNaphtha: 0.16, hcJet: 0.35, hcDiesel: 0.52 }, hvgo: { lpg: 0.06, hcNaphtha: 0.18, hcJet: 0.32, hcDiesel: 0.52 }, cokerGo: { lpg: 0.07, hcNaphtha: 0.2, hcJet: 0.3, hcDiesel: 0.5 } },
    h2: { lvgo: -1.8, hvgo: -2.1, cokerGo: -2.6 },
    purpose: "Cracks vacuum gas oil under high hydrogen pressure into clean jet and diesel, swelling the volume as hydrogen is added.",
    card: ["Where the FCC makes gasoline, the hydrocracker makes middle distillates: clean, high-cetane diesel and jet.",
      "It runs at 100–200 bar with lots of hydrogen, about 2,000 scf a barrel: the single biggest hydrogen consumer in a refinery.",
      "The products gain volume, about 8%, because hydrogen is added: a hydrocracker can make more than a barrel of product from a barrel of feed."] },
  alky: { name: "Alkylation unit", short: "Alky", kind: "octane", feeds: ["c4"], opex: 4,
    yields: { c4: { alkylate: 0.9, lpg: 0.1 } },
    h2: {},
    purpose: "Joins the FCC's butenes to isobutane, over hydrofluoric or sulphuric acid, into alkylate: the cleanest high-octane blendstock.",
    card: ["The FCC's C4 olefins would otherwise be LPG; alkylation turns them into premium gasoline.",
      "Butenes and isobutane react over a strong acid into branched C8 paraffins: octane 95, low vapour pressure, no sulphur, no aromatics.",
      "The acid is the hazard: HF units are fenced and sulphuric units ship acid by the truckload for regeneration."] },
  cnht: { name: "FCC naphtha post-treater", short: "CN-HDS", kind: "treating", feeds: ["catNaphtha"], opex: 0.8, carry: { ron: -2, s: 10 },
    yields: { catNaphtha: { catNaphthaT: 0.99, gas: 0.01 } },
    h2: { catNaphtha: -0.15 },
    purpose: "Takes the sulphur out of FCC naphtha while saturating as few of its olefins as possible, since they are its octane.",
    card: ["FCC naphtha is about half the gasoline pool and nearly all its sulphur.",
      "A selective hydrotreater removes the sulphur but keeps the olefins, at a cost of a point or two of octane.",
      "Without it, a cracking refinery cannot make 10 ppm gasoline."] },
  dht: { name: "Diesel hydrotreater", short: "DHT", kind: "treating", feeds: ["lgo", "hgo", "lco", "cokerGo", "fuelOilCutter", "kero"], opex: 1.5, carry: { cet: 1, s: 8 },
    yields: { lgo: { ulsd: 0.99, gas: 0.01 }, hgo: { ulsd: 0.98, gas: 0.02 }, lco: { ulsd: 0.98, gas: 0.02 }, cokerGo: { ulsd: 0.97, gas: 0.03 }, fuelOilCutter: { ulsd: 0.98, gas: 0.02 }, kero: { ulsd: 0.99, gas: 0.01 } },
    h2: { lgo: -0.3, hgo: -0.45, lco: -0.9, cokerGo: -1.0, fuelOilCutter: -0.6, kero: -0.15 },
    purpose: "Takes gas oil to 10 ppm sulphur over a catalyst with hydrogen, so it can be sold as road diesel.",
    card: ["Straight-run gas oil holds about 1% sulphur; the road spec is 0.001%. The hydrotreater is where the difference goes.",
      "Cracked gas oils, LCO and coker gas oil, take far more hydrogen: aromatics and olefins have to be saturated too.",
      "The pool's cetane is whatever its parts bring: straight-run gas oil around 50, LCO in the 20s. The treater does little about that."] },
  kht: { name: "Kerosene treater", short: "KHT", kind: "treating", feeds: ["kero"], opex: 1, carry: { cet: 0, s: 10 },
    yields: { kero: { jet: 0.99, gas: 0.01 } },
    h2: { kero: -0.15 },
    purpose: "Brings kerosene to the jet specification: sulphur, mercaptans and acidity out.",
    card: ["Jet fuel is kerosene with its sulphur and mercaptans removed and its acidity, freeze point and smoke point in spec.",
      "Sweet kerosene may need only a sweetening unit (Merox); sour kerosene needs a proper hydrotreater.",
      "Jet usually prices above diesel, so a refinery sends every barrel of kerosene it can to the jet pool."] },
  coker: { name: "Delayed coker", short: "Coker", kind: "conversion", feeds: ["vacResid"], opex: 5,
    yields: { vacResid: { gas: 0.08, lpg: 0.04, cokerNaphtha: 0.16, cokerGo: 0.45, coke: 0.25 } },
    h2: {},
    purpose: "Heats vacuum residue until it cracks, leaving solid coke in a drum and sending the lighter products on to be treated and cracked.",
    card: ["The deepest conversion a refinery can do: residue goes in, nothing heavier than gas oil comes out, and the carbon ends up as coke.",
      "Two drums alternate: one fills with coke for about a day while the other is cut out with high-pressure water.",
      "Everything the coker makes is sour and olefinic, so it all needs hydrotreating before it can be sold or cracked."] },
  visbreaker: { name: "Visbreaker", short: "Visb", kind: "conversion", feeds: ["vacResid"], opex: 1.5,
    yields: { vacResid: { gas: 0.02, cokerNaphtha: 0.05, fuelOilCutter: 0.12, visResid: 0.81 } },
    h2: {},
    purpose: "Cracks vacuum residue mildly to cut its viscosity, so less valuable gas oil has to be blended in to make fuel oil.",
    card: ["A gentle thermal cracker: a short, hot pass that breaks just enough of the residue to thin it.",
      "The point is to save cutter stock: fuel oil needs a viscosity the residue doesn't have, and the alternative is blending in gas oil worth twice as much.",
      "It makes a little naphtha and gas oil on the way, both sour."] },
  bitumen: { name: "Bitumen blowing", short: "Bitumen", kind: "conversion", feeds: ["vacResid"], opex: 1,
    yields: { vacResid: { bitumen: 1 } },
    h2: {},
    purpose: "Blows air through vacuum residue from an asphaltic crude to make road bitumen.",
    card: ["Only some crudes make good bitumen: the heavy, naphthenic, asphaltene-rich ones.",
      "Air oxidises and polymerises the residue, raising its softening point to what roads need.",
      "In the right market, bitumen pays more than the fuel oil the residue would otherwise become."] },
  smr: { name: "Hydrogen plant", short: "SMR", kind: "utility", feeds: [], opex: 0,
    purpose: "Reforms natural gas with steam into hydrogen, for everything the catalytic reformer's hydrogen can't cover.",
    card: ["Steam methane reforming: methane and steam over nickel at 900 °C give hydrogen and carbon monoxide, shifted to more hydrogen and CO2.",
      "A hydrocracker or an HVO unit needs far more hydrogen than the reformer makes, so most conversion refineries have one.",
      "It is also the refinery's biggest single source of CO2."] },
  sru: { name: "Sulphur recovery unit", short: "SRU", kind: "utility", feeds: [], opex: 0,
    purpose: "Turns the hydrogen sulphide from every hydrotreater into elemental sulphur, by the Claus process.",
    card: ["Every hydrotreater strips sulphur out as hydrogen sulphide; the amine units collect it and the Claus plant burns a third of it to SO2, which reacts with the rest to make sulphur.",
      "A sour-crude refinery makes hundreds of tonnes of sulphur a day, sold for sulphuric acid and fertiliser.",
      "Without it, the hydrotreaters could not run: the H2S has nowhere to go."] },
  hvoUnit: { name: "HVO unit", short: "HVO", kind: "renewable", feeds: ["vegOil"], opex: 8,
    yields: { vegOil: { hvo: 0.85, lpg: 0.05, hcNaphtha: 0.03 } },
    h2: { vegOil: -3.0 },
    purpose: "Hydrotreats vegetable oil or waste fat into renewable diesel: the fatty acids' oxygen is removed and the chains saturated to paraffins.",
    card: ["The same chemistry as a diesel hydrotreater, with a very different feed: triglycerides from rapeseed, palm or used cooking oil.",
      "Hydrogen removes the oxygen as water and CO2 and saturates the chains: the product is paraffinic diesel with cetane in the 70s, plus propane and some naphtha.",
      "It needs about 3,000 scf of hydrogen a barrel, and it earns the compliance ticket under RED, the THG-quota or the RTFO on top of the diesel price."] },
};

// ---------- the products and their specs ----------
// accept: which streams can go to the pool; spec: what the blend must meet to sell at the pool's price; fallback: where
// an off-spec blend sells instead. Prices are $/bbl.
export const POOLS = {
  gasoline: { name: "Gasoline", price: 100, accept: ["lsr", "reformate", "isomerate", "catNaphtha", "catNaphthaT", "alkylate", "hcNaphtha", "ethanol", "cokerNaphtha", "hsr", "hsrT"], spec: { ronMin: 95, sMax: 10 }, fallback: "naphtha",
    note: "RON 95 and 10 ppm sulphur, in Europe. Off-spec, it sells as naphtha." },
  naphtha: { name: "Petrochemical naphtha", price: 74, accept: ["lsr", "hsr", "hsrT", "hcNaphtha", "isomerate", "reformate", "catNaphthaT", "cokerNaphtha", "catNaphtha", "alkylate"], note: "Steam-cracker feed. Where gasoline blendstocks go when they don't make gasoline." },
  jet: { name: "Jet fuel", price: 108, accept: ["jet", "hcJet", "kero"], spec: { jetOnly: true }, fallback: "diesel", note: "Only treated kerosene and hydrocracker jet qualify. Untreated kerosene drops to the diesel pool." },
  diesel: { name: "Diesel", price: 110, accept: ["ulsd", "hcDiesel", "hvo", "fame", "lgo", "hgo", "lco", "kero", "jet", "hcJet", "cokerGo", "fuelOilCutter"], spec: { cetMin: 51, sMax: 10 }, fallback: "fuelOil",
    note: "Cetane 51 and 10 ppm sulphur (EN 590). Off-spec, it sells as fuel oil." },
  fuelOil: { name: "Fuel oil", price: 70, accept: ["atmResid", "vacResid", "visResid", "slurry", "lgo", "hgo", "lco", "cokerGo", "fuelOilCutter", "ulsd", "kero", "lvgo", "hvgo"], spec: { sMax: 5000 }, fallback: "hsfo",
    note: "VLSFO, 0.5% sulphur for ships since IMO 2020. Sourer blends sell as high-sulphur fuel oil at a discount." },
  hsfo: { name: "High-sulphur fuel oil", price: 52, accept: ["atmResid", "vacResid", "visResid", "slurry", "lco", "cokerGo", "fuelOilCutter", "lvgo", "hvgo", "hgo", "lgo", "kero", "ulsd"], note: "Bunker fuel for ships with scrubbers, and power plants. The cheapest home for residue." },
  lpg: { name: "LPG", price: 50, accept: ["lpg", "c4"], note: "Propane and butane." },
  propylene: { name: "Propylene", price: 95, accept: ["propylene"], note: "Polymer-grade propylene for polypropylene." },
  bitumen: { name: "Bitumen", price: 75, accept: ["bitumen"], note: "Road bitumen." },
  coke: { name: "Petroleum coke", price: 15, accept: ["coke"], note: "Fuel-grade coke, priced per barrel of residue it came from." },
  gasPool: { name: "Refinery fuel", price: 20, accept: ["gas"], note: "Fuel gas burned in the furnaces: worth natural gas, no more." },
  hvo: { name: "HVO / renewable diesel", price: 190, accept: ["hvo"], note: "Renewable diesel with its compliance ticket: around double a barrel of fossil diesel." },
  sulphur: { name: "Sulphur", price: 8, accept: ["sulphur"], note: "Per barrel-equivalent of the H2S it came from; a small credit." },
};
export const H2_PRICE = 1.6;       // $ per thousand scf from the hydrogen plant
export const RENEWABLE_FEED = { vegOil: 140, ethanol: 85, fame: 120 };   // $/bbl bought in

// ---------- crudes ----------
// cuts: the crude unit's yields; vgoShare: how much of the atmospheric residue the vacuum unit lifts as VGO
export const CRUDES = {
  brent: { name: "Brent", api: 38, sulphur: 0.4, price: 79, vgoShare: 0.58,
    cuts: { gas: 0.01, lpg: 0.02, lsr: 0.07, hsr: 0.16, kero: 0.12, lgo: 0.19, hgo: 0.08, atmResid: 0.35 },
    note: "The North Sea benchmark: light and sweet, a lot of naphtha and distillate, little residue." },
  wti: { name: "WTI", api: 40, sulphur: 0.3, price: 77, vgoShare: 0.6,
    cuts: { gas: 0.01, lpg: 0.025, lsr: 0.085, hsr: 0.175, kero: 0.11, lgo: 0.18, hgo: 0.08, atmResid: 0.335 },
    note: "West Texas Intermediate: lighter and sweeter still, with a Cushing delivery point." },
  bonny: { name: "Bonny Light", api: 35, sulphur: 0.15, price: 80, vgoShare: 0.55,
    cuts: { gas: 0.01, lpg: 0.015, lsr: 0.05, hsr: 0.13, kero: 0.14, lgo: 0.23, hgo: 0.09, atmResid: 0.335 },
    note: "Nigeria's sweet, distillate-rich crude: kerosene and gas oil, almost no sulphur." },
  urals: { name: "Urals", api: 31, sulphur: 1.6, price: 68, vgoShare: 0.52,
    cuts: { gas: 0.01, lpg: 0.015, lsr: 0.05, hsr: 0.12, kero: 0.1, lgo: 0.17, hgo: 0.08, atmResid: 0.455 },
    note: "Russia's medium sour export blend: more residue, and sulphur that has to come out everywhere." },
  arabHeavy: { name: "Arab Heavy", api: 28, sulphur: 2.8, price: 68, vgoShare: 0.48,
    cuts: { gas: 0.01, lpg: 0.01, lsr: 0.04, hsr: 0.1, kero: 0.09, lgo: 0.14, hgo: 0.07, atmResid: 0.54 },
    note: "Saudi heavy sour: half of it is residue. Only a coker or a hydrocracker makes it pay." },
  maya: { name: "Maya", api: 22, sulphur: 3.4, price: 60, vgoShare: 0.42, asphaltic: true,
    cuts: { gas: 0.01, lpg: 0.01, lsr: 0.03, hsr: 0.08, kero: 0.08, lgo: 0.12, hgo: 0.07, atmResid: 0.6 },
    note: "Mexico's heavy sour benchmark, cheap for a reason: coker feed, or bitumen." },
};
