// Generated by tools/build-sw.mjs: don't edit by hand.
// Keeps every file of every game on the device, so the games open and play offline. The version changes with
// any file, so devices fetch the new set in the background; it waits until the app is off screen to take over
// (see pwa.js). Requests to other sites (Firebase, for playing together) go straight to the network.
const VERSION = "fba873641d81";
const CACHE = `crates-${VERSION}`;
const FILES = [
  "./",
  "app.js",
  "apps.js",
  "bank.js",
  "cartel-ai.js",
  "cartel-engine.js",
  "cartel.css",
  "cartel.html",
  "cartel.js",
  "coop.js",
  "core.js",
  "delta-gen.js",
  "delta-worker.js",
  "delta.css",
  "delta.html",
  "delta.js",
  "flags.js",
  "fonts/archivo-latin-ext.woff2",
  "fonts/archivo-latin.woff2",
  "gen.js",
  "glyph.html",
  "icon.png",
  "icon.svg",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "index.html",
  "learn.js",
  "manifest.webmanifest",
  "net.js",
  "punt-gen.js",
  "punt.css",
  "punt.html",
  "punt.js",
  "pwa.js",
  "rooms.js",
  "run.js",
  "slate-gen.js",
  "slate-words.js",
  "slate.css",
  "slate.html",
  "slate.js",
  "solo.js",
  "style.css",
  "sync.js",
  "together.js",
  "view.js"
];

self.addEventListener("install", event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(FILES.map(f => new Request(f, { cache: "reload" })))));
});
self.addEventListener("activate", event => {
  event.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith("crates-") && k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener("message", event => { if (event.data === "take-over") self.skipWaiting(); });
self.addEventListener("fetch", event => {
  const url = new URL(event.request.url);
  if (event.request.method !== "GET" || url.origin !== self.location.origin) return;
  event.respondWith(caches.open(CACHE)
    .then(cache => cache.match(event.request, { ignoreSearch: true }))
    .then(hit => hit || fetch(event.request)));
});
