// Generated by tools/build-sw.mjs: don't edit by hand.
const VERSION = "4e008719b9bc";
const FILES = {
  "./": "3cc82bec3536",
  "app.js": "7b9bde81d6ea",
  "apps.js": "d72160188359",
  "arb.css": "983e6f5cfb0c",
  "arb.html": "d097d880ed9b",
  "arb.js": "1e37a0a8fa08",
  "arch-bank.js": "65cfd129f8f8",
  "art-bank.js": "17e229cd2d41",
  "artmarket-bank.js": "5d00fdb230a2",
  "bank.js": "6191c821ba17",
  "bavaria-bank.js": "54138ff7c647",
  "blend-engine.js": "67af4bdaa074",
  "blend.css": "f6e74a69dc63",
  "blend.html": "202de6fb8503",
  "blend.js": "f5be4988b0fb",
  "britain-bank.js": "f5b96a0b720e",
  "brut-data.js": "c27633b9b8b2",
  "brut-engine.js": "0a13a27305f9",
  "brut.css": "1ebb33ae2c59",
  "brut.html": "8577b4ef556e",
  "brut.js": "b37f0063179e",
  "calibre-3d.js": "2cac32809f2e",
  "calibre-draw.js": "a14771ee9176",
  "calibre-engine.js": "c57387bd060f",
  "calibre-lessons.js": "d0ae23c3ae24",
  "calibre-levels.js": "dff96c16ab1b",
  "calibre-quiz.js": "0e64ffb56b3c",
  "calibre-scenes.js": "a09aa85b0f65",
  "calibre.css": "6769c7550068",
  "calibre.html": "1f8633355e27",
  "calibre.js": "4799c7aed93d",
  "cartel-ai.js": "db0e465ad674",
  "cartel-engine.js": "b5d8b1686e66",
  "cartel.css": "3e115169cc7e",
  "cartel.html": "545ba5e34815",
  "cartel.js": "a69c6b4a003d",
  "chart-bank.js": "f46ad3197a52",
  "chart-countries.js": "57f9326e72d2",
  "chart-detail.js": "b35cfdd38d18",
  "chart-engine.js": "0812bd91a318",
  "chart-geo.js": "983806d4d42e",
  "chart-islands.js": "b61bdd129773",
  "chart.css": "294c9bf52b9e",
  "chart.html": "290887ebe0a1",
  "chart.js": "e7ee73438138",
  "chess-board.js": "13787a19c77a",
  "chess-pieces.js": "999b21bb93cb",
  "china-bank.js": "26f56a61cc1d",
  "chm-bank.js": "8fd0ffda88ae",
  "cities-bank.js": "c7e38914253e",
  "coop.js": "9941610f1705",
  "core.js": "e48e7aba4ed0",
  "crates.html": "8a9d40e53e4d",
  "cs-bank.js": "35306a39d788",
  "days.js": "c218ca95dae5",
  "deck.css": "3407abe22b65",
  "deck.html": "d2560895dbf0",
  "deck.js": "a4a2d2af15d8",
  "delta-gen.js": "b54d9c60809a",
  "delta-worker.js": "e09e303851e9",
  "delta.css": "375b8036992d",
  "delta.html": "6babaf648781",
  "delta.js": "406869923b34",
  "dropdown.css": "1b5fc48c39e8",
  "dropdown.js": "a13c7e283a31",
  "eco-bank.js": "ca085cafe691",
  "flags-bank.js": "1f8da6003334",
  "flags.js": "459350e0b9fb",
  "fonts/archivo-latin-ext.woff2": "837705d41279",
  "fonts/archivo-latin.woff2": "258a93fe93ae",
  "fonts/twemoji-flags.woff2": "1fe9b7f7f114",
  "gen.js": "e43fc54bd052",
  "glyph.html": "8dda67f6f15d",
  "harbour-3d.js": "c02f49f6922e",
  "harbour-campaign.js": "cd20f3bff9ed",
  "harbour-engine.js": "26508f321671",
  "harbour-flat.js": "b2590c76786a",
  "harbour-levels.js": "de88c7b6d8d7",
  "harbour-season-ui.js": "d2ef7f95817f",
  "harbour-season.js": "8f870552e091",
  "harbour-sound.js": "2df11f9b3f5b",
  "harbour-tape.js": "b9ac03b58cc6",
  "harbour-world-ui.js": "1c1e9eddeeee",
  "harbour.css": "4d87cf4843da",
  "harbour.html": "75eab4935a23",
  "harbour.js": "0df8284117c7",
  "home.js": "bf3b9ac43918",
  "icon.png": "139853f398ff",
  "icon.svg": "33087beee1a4",
  "icons/icon-192.png": "645f8c5ab354",
  "icons/icon-512.png": "f25087a350db",
  "icons/icon-maskable-512.png": "7ae31efb0916",
  "index.html": "3cc82bec3536",
  "kb-index.js": "61dbfde4c15a",
  "kb/entities.js": "6d4ef3b814e5",
  "kb/items/sequences.js": "d799122effb4",
  "kb/links.js": "6d8314672c82",
  "known.js": "3aa7292123a8",
  "learn.js": "c255f0c737dc",
  "ledger-log.js": "e87dad1f68af",
  "ledger.css": "df19b3329ce8",
  "ledger.html": "50b0f98409f5",
  "ledger.js": "00be7af2c5ff",
  "lexicon.css": "7dde3b2f7eeb",
  "lexicon.html": "da598deb10bd",
  "lexicon.js": "f03437d860dc",
  "lit-bank.js": "908918969c4b",
  "loading.js": "3188b3dcc9da",
  "logo-modern.svg": "21517894f77d",
  "logo.svg": "97740c27729e",
  "manifest-engine.js": "1dcbe2af41e2",
  "manifest.css": "f6840c9183d2",
  "manifest.html": "344b2252b920",
  "manifest.js": "7843462f2249",
  "manifest.webmanifest": "b1b2c9942118",
  "maths-bank.js": "a0bb6c7470d2",
  "menu.js": "b9880ab28cba",
  "merchants-bank.js": "c4ed2532187c",
  "myth-bank.js": "0e18afeea82d",
  "net.js": "740671007b8b",
  "order.css": "679ee3b5e93e",
  "order.html": "5c7e78a98396",
  "order.js": "947c2322d9ce",
  "origin.css": "a93e82529697",
  "origin.html": "6e1ac1380cf9",
  "origin.js": "dcc4c503f482",
  "parley-courses.js": "a7251286768b",
  "parley.css": "d57bb24624df",
  "parley.html": "e20dbc898f37",
  "parley.js": "4f0820eaec72",
  "patterns-bank.js": "8e96414cd810",
  "phil-bank.js": "31f6be9f1f50",
  "phy-bank.js": "a1154d02ce9e",
  "pics-list.js": "6095b8d93983",
  "pics.js": "14ac2aeca3ba",
  "pile.js": "814cbc087791",
  "pipes-engine.js": "4d29097184c5",
  "pipes-run.js": "47c9e5e45ddc",
  "pipes.css": "a36d756b4be6",
  "pipes.html": "7a0c06dab465",
  "pipes.js": "7220db90c792",
  "punt-gen.js": "55421edbb4ca",
  "punt.css": "342065008471",
  "punt.html": "803b32eeb1ff",
  "punt.js": "fe95f3bd16cd",
  "puzzles/band-0600.txt": "e86486d71c8b",
  "puzzles/band-0800.txt": "5d6d49778297",
  "puzzles/band-1000.txt": "d54d60c5bcc8",
  "puzzles/band-1200.txt": "103d0ed14fd7",
  "puzzles/band-1400.txt": "14cee9470e40",
  "puzzles/band-1600.txt": "22ad754a3f7f",
  "puzzles/band-1800.txt": "92506b5060db",
  "puzzles/band-2000.txt": "695e3549eda2",
  "puzzles/band-2200.txt": "68e40ea8a1f8",
  "puzzles/band-2400.txt": "b32bc0315d7a",
  "puzzles/index.json": "704a0a2ceb5b",
  "pwa.js": "5bf8cbaff3a5",
  "question-flags.js": "074bdd52c399",
  "quote-bank.js": "579072c09690",
  "quote-engine.js": "ea679dbce591",
  "quote.css": "1f3d75ea089d",
  "quote.html": "f8a1854674ca",
  "quote.js": "368f452fdb19",
  "reasoning-bank.js": "50e98f9617bc",
  "refinery-data.js": "fd0f54538f65",
  "refinery-engine.js": "e33baedfae4c",
  "refinery-levels.js": "553997545ec0",
  "refinery.css": "2d4d27f262de",
  "refinery.html": "3412111b2f23",
  "refinery.js": "2d25bc0ca739",
  "refining-bank.js": "86ed755d4b61",
  "rel-bank.js": "265b47d5d06f",
  "rete.svg": "7ef0a266eeab",
  "rich.js": "c8fb6dbe0a54",
  "rooms.js": "61add3f36b8f",
  "run.js": "459929ceaec0",
  "rush.css": "988e74bb246b",
  "rush.html": "80c38febd2f4",
  "rush.js": "da3763566a3c",
  "sayings-bank.js": "bd17af480600",
  "sextant.svg": "c1f220275352",
  "skiing-bank.js": "ad6d70add79a",
  "slate-defs.js": "8518d4433864",
  "slate-gen.js": "4b4567ca4580",
  "slate-solve.js": "83feb15f92ed",
  "slate-words.js": "90f20e4932bc",
  "slate-worker.js": "86d42d2ef4c7",
  "slate.css": "d38af5e72d3e",
  "slate.html": "9bb4a74ff2bf",
  "slate.js": "5a8855fe2c22",
  "solo.js": "6ad871c8e961",
  "spot-engine.js": "5a5fc44a7138",
  "spot.css": "711fdf44fab7",
  "spot.html": "abb4e106f623",
  "spot.js": "d829a8b51250",
  "style.css": "9183731b8c8f",
  "suite.js": "f7208d5e137f",
  "survey-engine.js": "5c0dca2aa742",
  "survey.css": "4db078d569a0",
  "survey.html": "984920ba6b4a",
  "survey.js": "e68f415052bd",
  "swiss-bank.js": "cebb7f65fa4c",
  "sync.js": "52ac6635f79e",
  "theme.js": "426ce9875545",
  "themes.css": "0a6401aefd0b",
  "titles-bank.js": "af1660867009",
  "together.js": "3d2ba421a446",
  "typing.js": "05ba6624ee8c",
  "vendor/Temml.woff2": "086f6b222043",
  "vendor/chess.js": "d37d269104b4",
  "vendor/temml.css": "216ac9f4d6a5",
  "vendor/temml.min.js": "7e4c646e0bf9",
  "vendor/three.js": "ea6ac48039a3",
  "view.js": "1400020d125a",
  "voice.js": "35c609a86060",
  "watches-bank.js": "28225420095c",
  "wide.js": "fe42a825e91c",
  "wine-bank.js": "62e2096ddffc",
  "words-bank.js": "30b7555b6bb7",
  "world.js": "dc37aa1d24fc"
};

// The service worker. tools/build-sw.mjs writes it into sw.js after VERSION and FILES: every file the app needs
// offline (tools/offline.mjs), each with the first 12 hex digits of the SHA-1 of its bytes. It keeps them all on the
// device, so every page opens and plays with no connection, from the home screen too. Requests to other sites
// (Firebase, for playing together) go to the network; Wikipedia's pictures are kept once they've been shown.
//
// An update downloads only what changed. A file whose bytes are already on the device, in an older version's copy,
// is copied across instead of fetched again (the app is about 13 MB and changes many times a day; every update once
// fetched all of it). What it does fetch it asks for at an address carrying the file's hash, so no cache on the way,
// the browser's or the site's servers', can answer with an older copy. A new version waits until the app is off
// screen to take over (pwa.js), and an older version's copy is deleted only once the new one is whole.
/* global VERSION, FILES */

const CACHE = `crates-${VERSION}`;
const PICS = "crates-pics-2";          // pictures from Wikipedia, kept once shown (pics-2: the first could hold refused thumbnails)
const KEEP = [PICS];                   // copies an update leaves alone
const TYPES = { html: "text/html", js: "text/javascript", mjs: "text/javascript", css: "text/css", json: "application/json",
  webmanifest: "application/manifest+json", txt: "text/plain", svg: "image/svg+xml", png: "image/png", woff2: "font/woff2" };
const typeOf = (file, res) => res.headers.get("Content-Type") || TYPES[(file.match(/\.(\w+)$/) || ["", "html"])[1]] || "application/octet-stream";

/** The first 12 hex digits of the SHA-1 of some bytes, as tools/build-sw.mjs hashes each file; null where the
 *  browser can't hash (then nothing is copied, and an update fetches every file, as every update once did). */
async function hashOf(bytes) {
  try {
    const d = new Uint8Array(await crypto.subtle.digest("SHA-1", bytes));
    return Array.from(d.subarray(0, 6), b => b.toString(16).padStart(2, "0")).join("");
  } catch { return null; }
}
/** A file's bytes as a response of their own: only the type comes along (not a redirect, not an encoding). */
const stored = (bytes, type) => new Response(bytes, { headers: { "Content-Type": type } });

/**
 * Makes this version's copy whole: each file already there with the right bytes is left, one held with the right
 * bytes by an older copy is copied across, and the rest is fetched, six at a time. Throws if a fetch fails.
 */
async function fill() {
  const cache = await caches.open(CACHE);
  const others = await Promise.all((await caches.keys()).filter(k => k.startsWith("crates-") && k !== CACHE && !KEEP.includes(k)).map(k => caches.open(k)));
  const want = Object.entries(FILES);
  const one = async ([file, hash]) => {
    const key = new Request(file);                       // its address in the app's folder (the worker's own)
    for (const source of [cache, ...others]) {
      const hit = await source.match(key);
      if (!hit) continue;
      const bytes = await hit.arrayBuffer();
      if (await hashOf(bytes) !== hash) continue;        // another version of the file
      if (source !== cache) await cache.put(key, stored(bytes, typeOf(file, hit)));
      return;
    }
    const res = await fetch(`${file}?v=${hash}`, { cache: "no-store" });
    if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`);
    // kept even if its bytes aren't the ones listed (the site may already serve a newer push): the next version,
    // finding them wrong, fetches it again rather than copying it
    await cache.put(key, stored(await res.arrayBuffer(), typeOf(file, res)));
  };
  let next = 0;
  const lane = async () => { while (next < want.length) await one(want[next++]); };
  await Promise.all(Array.from({ length: 6 }, lane));
}
/** True when this version's copy holds every file. */
async function whole() {
  const have = new Set((await (await caches.open(CACHE)).keys()).map(r => r.url));
  return Object.keys(FILES).every(f => have.has(new URL(f, self.location).href));
}

self.addEventListener("install", event => {
  event.waitUntil(fill().then(whole).then(ok => { if (!ok) throw new Error("the copy was emptied while it filled"); }));
});
self.addEventListener("activate", event => event.waitUntil((async () => {
  // an older version taking over while this one filled can have deleted this one's copy: it's made whole first, and
  // the older copies go only once it is (offline they stay, and answer for whatever this one lacks)
  if (!await whole()) await fill().catch(() => {});
  if (await whole()) for (const k of await caches.keys()) if (k.startsWith("crates-") && k !== CACHE && !KEEP.includes(k)) await caches.delete(k);
  await self.clients.claim();
})()));
self.addEventListener("message", event => { if (event.data === "take-over") self.skipWaiting(); });

// pictures from Wikipedia (the API's answers and the images, thumbnails from thumb.wikimedia.org): an image fetched
// by an <img> comes back opaque (no CORS), which can still be kept and given back to an <img>
const isPicture = url => (url.hostname === "en.wikipedia.org" && url.pathname === "/w/api.php" && url.searchParams.get("prop") === "pageimages")
  || url.hostname === "upload.wikimedia.org" || url.hostname === "thumb.wikimedia.org";
async function picture(request) {
  const cache = await caches.open(PICS), hit = await cache.match(request);
  if (hit) return hit;
  const res = await fetch(request);
  if (res.ok || res.type === "opaque") cache.put(request, res.clone()).catch(() => {});   // kept as it's shown, not before
  return res;
}
/**
 * A file of the app, whatever ?query its address carries: this version's copy, else any version's (should this one
 * lack it), else the network. Offline, a page that isn't kept opens the games screen instead of the browser's error,
 * since an app on the home screen has no Back to leave it by.
 */
async function answer(request) {
  const cache = await caches.open(CACHE);
  const hit = await cache.match(request, { ignoreSearch: true }) || await caches.match(request, { ignoreSearch: true });
  if (hit) return hit;
  try { return await fetch(request); } catch (e) {
    const home = request.mode === "navigate" && (await cache.match("./") || await caches.match("./"));
    if (home) return home;
    throw e;
  }
}
self.addEventListener("fetch", event => {
  const request = event.request, url = new URL(request.url);
  if (request.method !== "GET") return;
  if (isPicture(url)) event.respondWith(picture(request));
  else if (url.origin === self.location.origin) event.respondWith(answer(request));
});
