// Generated by tools/build-sw.mjs: don't edit by hand.
// Keeps every file of every game on the device, so the games open and play offline. The version changes with
// any file, so devices fetch the new set in the background; it waits until the app is off screen to take over
// (see pwa.js). Requests to other sites (Firebase, for playing together) go straight to the network.
const VERSION = "c244c718a454";
const CACHE = `crates-${VERSION}`;
const FILES = [
  "./",
  "app.js",
  "apps.js",
  "art-bank.js",
  "bank.js",
  "blend-engine.js",
  "blend.css",
  "blend.html",
  "blend.js",
  "brut-data.js",
  "brut-engine.js",
  "brut.css",
  "brut.html",
  "brut.js",
  "cartel-ai.js",
  "cartel-engine.js",
  "cartel.css",
  "cartel.html",
  "cartel.js",
  "chart-bank.js",
  "chart-engine.js",
  "chart-geo.js",
  "chart.css",
  "chart.html",
  "chart.js",
  "chess-board.js",
  "chess-pieces.js",
  "chm-bank.js",
  "cities-bank.js",
  "coop.js",
  "core.js",
  "cs-bank.js",
  "deck.css",
  "deck.html",
  "deck.js",
  "delta-gen.js",
  "delta-worker.js",
  "delta.css",
  "delta.html",
  "delta.js",
  "eco-bank.js",
  "flags-bank.js",
  "flags.js",
  "fonts/archivo-latin-ext.woff2",
  "fonts/archivo-latin.woff2",
  "gen.js",
  "glyph.html",
  "icon.png",
  "icon.svg",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "index.html",
  "learn.js",
  "manifest-engine.js",
  "manifest.css",
  "manifest.html",
  "manifest.js",
  "manifest.webmanifest",
  "maths-bank.js",
  "net.js",
  "parley-courses.js",
  "parley.css",
  "parley.html",
  "parley.js",
  "patterns-bank.js",
  "phil-bank.js",
  "phy-bank.js",
  "pics.js",
  "pile.js",
  "pipes-engine.js",
  "pipes.css",
  "pipes.html",
  "pipes.js",
  "punt-gen.js",
  "punt.css",
  "punt.html",
  "punt.js",
  "pwa.js",
  "quote-bank.js",
  "quote-engine.js",
  "quote.css",
  "quote.html",
  "quote.js",
  "reasoning-bank.js",
  "refinery-data.js",
  "refinery-engine.js",
  "refinery-levels.js",
  "refinery.css",
  "refinery.html",
  "refinery.js",
  "refining-bank.js",
  "rel-bank.js",
  "rich.js",
  "rooms.js",
  "run.js",
  "rush.css",
  "rush.html",
  "rush.js",
  "slate-gen.js",
  "slate-solve.js",
  "slate-words.js",
  "slate-worker.js",
  "slate.css",
  "slate.html",
  "slate.js",
  "solo.js",
  "spot-engine.js",
  "spot.css",
  "spot.html",
  "spot.js",
  "style.css",
  "survey-engine.js",
  "survey.css",
  "survey.html",
  "survey.js",
  "sync.js",
  "together.js",
  "vendor/Temml.woff2",
  "vendor/chess.js",
  "vendor/temml.css",
  "vendor/temml.min.js",
  "view.js",
  "wine-bank.js",
  "words-bank.js",
  "world.js"
];

self.addEventListener("install", event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(FILES.map(f => new Request(f, { cache: "reload" })))));
});
self.addEventListener("activate", event => {
  event.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith("crates-") && k !== CACHE && k !== PUZZLES && k !== PICS).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener("message", event => { if (event.data === "take-over") self.skipWaiting(); });
// The chess puzzle bands (puzzles/*.txt) are big and rarely change: fetched when a run needs them and kept in a
// cache of their own, which an app update leaves alone.
const PUZZLES = "crates-puzzles-1", PICS = "crates-pics-1";
self.addEventListener("fetch", event => {
  if (event.request.method === "GET" && new URL(event.request.url).pathname.includes("/puzzles/")) {
    event.respondWith(caches.open(PUZZLES).then(cache => cache.match(event.request).then(hit => hit || fetch(event.request).then(res => { if (res.ok) cache.put(event.request, res.clone()); return res; }))));
    return;
  }
  const url = new URL(event.request.url);
  // pictures from Wikipedia (summaries and thumbnails) are kept once fetched, in a cache of their own
  if (event.request.method === "GET" && (url.hostname === "en.wikipedia.org" && url.pathname.startsWith("/api/rest_v1/page/summary/") || url.hostname === "upload.wikimedia.org")) {
    event.respondWith(caches.open(PICS).then(cache => cache.match(event.request).then(hit => hit || fetch(event.request).then(res => { if (res.ok) cache.put(event.request, res.clone()); return res; }))));
    return;
  }
  if (event.request.method !== "GET" || url.origin !== self.location.origin) return;
  event.respondWith(caches.open(CACHE)
    .then(cache => cache.match(event.request, { ignoreSearch: true }))
    .then(hit => hit || fetch(event.request)));
});
