// Punt's art-market questions (artmarket-bank.js is written from this; the build adds the houses', dealers' and forgers'
// own questions from kb/entities.js). about: the entities a question is about. o: options, a: the right ones.
export const STAGES = [{"id":"auctions","label":"How auctions work"},{"id":"records","label":"Records"},{"id":"dealers","label":"Houses and dealers"},{"id":"provenance","label":"Provenance and loot"},{"id":"fakes","label":"Fakes"},{"id":"fairs","label":"Fairs"}];
export const ITEMS = [
{"id":"AM-A01","lv":"auctions","d":2,"area":"How auctions work","q":"At auction, the hammer price is","o":["the seller's secret minimum for the lot","the house's estimate of what it will fetch","the price with premium, taxes and fees","the winning bid, before the buyer's premium"],"a":[3],"s":1,"x":"The buyer pays the hammer price plus the premium (and any taxes); the seller gets the hammer price less the seller's commission."},
{"id":"AM-A02","lv":"auctions","d":2,"area":"How auctions work","q":"A reserve is","o":["the price the house guarantees the seller","a bid left with the auctioneer in advance","the deposit a bidder pays for a paddle","the seller's confidential minimum price"],"a":[3],"s":1,"x":"It's kept secret and set at or below the low estimate; the house's guarantee and the absentee (commission) bid are other things."},
{"id":"AM-A03","lv":"auctions","d":3,"area":"How auctions work","q":"'Chandelier bidding' is","o":["bidding by phone from abroad, through the house's staff","the auctioneer taking bids from no one, up to the reserve","the house bidding on lots it has guaranteed itself","raising a paddle high, so the rostrum sees it under the lights"],"a":[1],"s":1,"x":"Allowed below the reserve, on the seller's behalf; the auctioneer looks at a chandelier, or the back of the room, and calls a bid."},
{"id":"AM-A04","lv":"auctions","d":2,"area":"How auctions work","q":"A lot that fails to reach its reserve is","o":["knocked down","bought in","withdrawn","passed"],"a":[1],"s":1,"x":"It goes back to the seller, who usually pays a fee. 'Knocked down' means sold; 'withdrawn' means taken out before the sale."},
{"id":"AM-A05","lv":"auctions","d":4,"area":"How auctions work","q":"A third-party guarantee (an irrevocable bid) is, in a trader's terms,","o":["a put sold to the seller: a promise to buy at a set price, for a fee","a call bought on the lot: the right to buy it at the low estimate","a loan against the work, repaid from the proceeds of the sale","an insurance policy against damage on the way to the saleroom"],"a":[0],"s":1,"x":"The guarantor promises to buy at the guaranteed price if no one bids higher; if outbid, they're paid a financing fee from the premium."},
{"id":"AM-A06","lv":"auctions","d":2,"area":"How auctions work","q":"The buyer's premium is","o":["the auction house's fee, on top of the hammer price","a bonus the house pays sellers for a high price","the extra a bidder pays to bid by telephone","the tax charged on art imported into the EU"],"a":[0],"s":1,"x":"Charged on a sliding scale, highest on the first slice of the price; import VAT is a separate charge on art brought in from outside the EU."},
{"id":"AM-A07","lv":"auctions","d":3,"area":"How auctions work","q":"Droit de suite (French: 'right to follow'), the artist's resale right, gives","o":["museums first refusal on works leaving the country","artists the right to buy their work back at cost","artists and their heirs a cut of each resale","collectors the right to resell without the artist's consent"],"a":[2],"s":1,"x":"In the EU since 2001 (in the UK from 2006), on resales through the trade, for 70 years after the artist's death. Pre-emption by museums is a different law."},
{"id":"AM-A08","lv":"auctions","d":3,"area":"How auctions work","q":"In the trade, a work that failed to sell at auction is","o":["fresh","shopped","flipped","burnt"],"a":[3],"s":1,"x":"Everyone has seen it go unsold, so it's hard to sell soon after. 'Fresh to the market' is the opposite; 'shopped' means offered round many dealers; 'flipped', resold fast."},
{"id":"AM-A09","lv":"auctions","d":3,"area":"How auctions work","q":"A catalogue raisonné is","o":["an auction catalogue with the house's estimates","a museum's register of its acquisitions","the full annotated list of an artist's known works","a dealer's list of works for sale"],"a":[2],"s":1,"x":"Being in it, or not, can make a work's value; the committees behind some have been sued for leaving works out."},
{"id":"AM-R01","lv":"records","d":2,"area":"Records","q":"The highest price ever paid for an artwork was for","o":["de Kooning's Interchange, $300m in 2015","Cézanne's The Card Players, $250m in 2011","Leonardo's Salvator Mundi, $450m in 2017","Warhol's Shot Sage Blue Marilyn, $195m in 2022"],"a":[2],"s":1,"x":"At Christie's New York; the de Kooning and the Cézanne were private sales, the Warhol the record for any 20th-century work at auction.","about":["salvator-mundi"]},
{"id":"AM-R02","lv":"records","d":2,"area":"Records","q":"In 2018, moments after it was sold at Sotheby's, Banksy's Girl with Balloon","o":["shredded itself halfway through its frame","was revealed as a fake by the artist himself","was stolen from the saleroom in the confusion","was found to have been bought by Banksy himself"],"a":[0],"s":1,"x":"Renamed Love is in the Bin, it sold again in 2021 for £18.6m, nearly eighteen times its 2018 price.","about":["banksy"]},
{"id":"AM-R03","lv":"records","d":3,"area":"Records","q":"Beeple's Everydays, sold at Christie's in 2021 for $69.3m, was","o":["an NFT: a digital image tied to a token","a mural cut from a wall in Manhattan","a sculpture made of a year's rubbish","a performance filmed every day for a year"],"a":[0],"s":1,"x":"A collage of 5,000 daily drawings over 13 years, paid for in the cryptocurrency Ether.","about":["everydays"]},
{"id":"AM-R04","lv":"records","d":3,"area":"Records","q":"Klimt's Adele Bloch-Bauer I left Austria in 2006 because","o":["Austria sold it to pay for the Belvedere's repairs","it was swapped for a Schiele in a museum exchange","an arbitration ruled it Nazi loot, owed to her niece","the Belvedere lent it to New York for good"],"a":[2],"s":1,"x":"Maria Altmann's case reached the US Supreme Court; she then sold it to Ronald Lauder for $135m. The story became the film Woman in Gold.","about":["portrait-of-adele-bloch-bauer-i","maria-altmann"]},
{"id":"AM-D01","lv":"dealers","d":3,"area":"Houses and dealers","q":"Paul Durand-Ruel is remembered for","o":["giving Cézanne his first solo exhibition, in Paris","championing Picasso and Braque's Cubism before 1914","selling Europe's old masters to American millionaires","rescuing the Impressionists and selling them in New York"],"a":[3],"s":1,"x":"He bought their work for years when no one else would. Cézanne's first show was Vollard's; Cubism was Kahnweiler's; the old masters Duveen's.","about":["paul-durand-ruel"]},
{"id":"AM-D02","lv":"dealers","d":3,"area":"Houses and dealers","q":"'Europe has a great deal of art, and America has a great deal of money' summed up the trade of","o":["Ernst Beyeler","Joseph Duveen","Leo Castelli","Paul Durand-Ruel"],"a":[1],"s":1,"x":"Duveen sold old masters to Frick, Mellon, Huntington and Morgan, with Bernard Berenson's attributions to back them.","about":["joseph-duveen"]},
{"id":"AM-D03","lv":"dealers","d":3,"area":"Houses and dealers","q":"Leo Castelli's gallery made the names of","o":["Monet, Renoir and Pissarro","Picasso, Braque and Gris","Rauschenberg, Johns and Lichtenstein","Pollock, Rothko and Still"],"a":[2],"s":1,"x":"From 1957 in New York. The Impressionists were Durand-Ruel's, the Cubists Kahnweiler's, and Pollock, Rothko and Still were shown by Betty Parsons.","about":["leo-castelli"]},
{"id":"AM-D04","lv":"dealers","d":2,"area":"Houses and dealers","q":"Art Basel was founded in 1970 by","o":["the city of Basel, to fill its trade-fair halls","Sotheby's, as a showcase for its private sales","the Swiss government, to rival the Venice Biennale","three Basel gallerists, Ernst Beyeler among them"],"a":[3],"s":1,"x":"Beyeler, Trudl Bruckner and Balz Hilt; Beyeler later opened the Fondation Beyeler at Riehen, outside Basel.","about":["art-basel","ernst-beyeler"]},
{"id":"AM-P01","lv":"provenance","d":3,"area":"Provenance and loot","q":"The Washington Principles of 1998 asked museums and states to","o":["return colonial-era objects to their countries","identify Nazi-looted art and settle fairly with heirs","ban sales of antiquities without export licences","register every artwork sold for over a million"],"a":[1],"s":1,"x":"Forty-four countries signed. The 1970 UNESCO convention covers illicit antiquities; colonial restitution is a later debate.","about":["washington-principles"]},
{"id":"AM-P02","lv":"provenance","d":2,"area":"Provenance and loot","q":"The Gurlitt hoard, found in a Munich flat in 2012, was","o":["the Bavarian royal collection, hidden in 1918","loot the Red Army had taken from Berlin","a forger's stock of fake Expressionists","art gathered by a dealer who sold for the Nazis"],"a":[3],"s":1,"x":"Hildebrand Gurlitt's son Cornelius had lived with it for decades; he left it to Kunstmuseum Bern.","about":["gurlitt-hoard"]},
{"id":"AM-P03","lv":"provenance","d":3,"area":"Provenance and loot","q":"The 'Degenerate Art' exhibition in Munich, 1937,","o":["mocked modern art seized from German museums","showed the art the regime wanted Germans to admire","auctioned Expressionist works abroad for currency","displayed art looted from occupied France"],"a":[0],"s":1,"x":"The admired art hung in the Great German Art Exhibition at the Haus der Kunst; the sale abroad was in Lucerne in 1939; the French loot went through the Jeu de Paume.","about":["degenerate-art-exhibition"]},
{"id":"AM-P04","lv":"provenance","d":3,"area":"Provenance and loot","q":"Most of the Benin Bronzes in Western museums were taken","o":["by French missionaries in the 1860s","by German traders, who bought them, in the 1880s","in a British punitive expedition of 1897","by Portuguese merchants in the 1500s"],"a":[2],"s":1,"x":"Thousands of works were looted from Benin City; Germany began returning its share to Nigeria in 2022."},
{"id":"AM-P05","lv":"provenance","d":3,"area":"Provenance and loot","q":"A freeport, like Geneva's, lets owners","o":["sell at auction without paying a buyer's premium","store art untaxed, in bond, for as long as they like","insure their art at a state-guaranteed rate","show their art in public without lending it out"],"a":[1],"s":1,"x":"Goods in a freeport haven't legally entered the country, so no import tax is due; critics say that also hides who owns what.","about":["geneva-freeport"]},
{"id":"AM-F01","lv":"fakes","d":3,"area":"Fakes","q":"After the war, Han van Meegeren escaped a charge of treason by","o":["showing he'd sold it on the Dutch government's orders","giving the painting back from Göring's collection","proving the 'Vermeer' he'd sold Göring was his own fake","proving he had never sold anything to the Germans"],"a":[2],"s":1,"x":"To prove it he painted another 'Vermeer' under guard; convicted of forgery instead, he died weeks after the verdict.","about":["han-van-meegeren"]},
{"id":"AM-F02","lv":"fakes","d":3,"area":"Fakes","q":"Wolfgang Beltracchi was caught when a 'Campendonk' of 1914 turned out to contain","o":["titanium white, a pigment not sold until years later","acrylic paint, invented after the artist's death","a canvas stamped by a shop that opened later","the forger's own fingerprint, under the varnish"],"a":[0],"s":1,"x":"He invented a whole provenance, the 'Jägers collection', and photographed his wife posing as her grandmother among the fakes.","about":["wolfgang-beltracchi"]},
{"id":"AM-F03","lv":"fakes","d":3,"area":"Fakes","q":"Knoedler, New York's oldest gallery, closed in 2011 after it had sold","o":["Nazi-looted old masters with forged papers","stolen Picassos out of a Swiss freeport","fake Rothkos and Pollocks painted in Queens","Banksy murals cut from London walls"],"a":[2],"s":1,"x":"About $80 million of them, painted by Pei-Shen Qian in his garage and passed off as from an unknown collector.","about":["knoedler"]},
{"id":"AM-F04","lv":"fakes","d":3,"area":"Fakes","q":"Elmyr de Hory, the subject of Orson Welles's F for Fake, forged mostly","o":["Dutch old masters, Vermeer above all","German Expressionists, for an invented collection","American Abstract Expressionists","drawings by Picasso, Matisse and Modigliani"],"a":[3],"s":1,"x":"The Vermeers were van Meegeren's, the Expressionists Beltracchi's, the Abstract Expressionists Pei-Shen Qian's.","about":["elmyr-de-hory"]},
{"id":"AM-X01","lv":"fairs","d":2,"area":"Fairs","q":"TEFAF, held each March in Maastricht, is the great fair for","o":["contemporary art and design","photography and new media","Asian art and ceramics","old masters and antiques"],"a":[3],"s":1,"x":"Contemporary art is Art Basel's and Frieze's; Paris Photo is the fair for photography.","about":["tefaf"]},
{"id":"AM-X02","lv":"fairs","d":3,"area":"Fairs","q":"documenta, in Kassel, is held","o":["every two years, through the summer","every five years, for a hundred days","every year, for a week each June","every ten years, across the city"],"a":[1],"s":1,"x":"Every two years is a biennale, like Venice's; every June is Art Basel; every ten years, the Skulptur Projekte in Münster.","about":["documenta"]},
{"id":"AM-X03","lv":"fairs","d":2,"area":"Fairs","q":"Art Basel's first three offshoots were in","o":["New York, Shanghai and London","Miami Beach, Hong Kong and Paris","Los Angeles, Singapore and Milan","Dubai, Tokyo and Berlin"],"a":[1],"s":1,"x":"Miami Beach in 2002, Hong Kong in 2013 (taking over Art HK), Paris in 2022 (taking FIAC's slot at the Grand Palais).","about":["art-basel"]}
];
