// Punt's flags questions (the bank flags-bank.js is written from this). about: the entities a question is about, where
// that's certain. o: the options, a: the right ones, s: how many to pick, x: the explanation, lv: the stage, d: 1–10.
export const STAGES = [{"id":"ea","label":"Well known"},{"id":"mi","label":"Less known"},{"id":"ha","label":"Obscure"}];
export const ITEMS = [
{"id":"FL-001","lv":"ea","d":2,"area":"Europe","q":"Whose flag is 🇫🇷?","o":["France","Greece","Germany","Russia"],"a":[0],"s":1,"x":"🇫🇷 is the flag of France.","about":["france"]},
{"id":"FL-002","lv":"ea","d":2,"area":"Europe","q":"Whose flag is 🇩🇪?","o":["France","Germany","Greece","United Kingdom"],"a":[1],"s":1,"x":"🇩🇪 is the flag of Germany.","about":["germany"]},
{"id":"FL-003","lv":"ea","d":2,"area":"Europe","q":"Whose flag is 🇮🇹?","o":["France","United Kingdom","Italy","Greece"],"a":[2],"s":1,"x":"🇮🇹 is the flag of Italy.","about":["italy"]},
{"id":"FL-004","lv":"ea","d":2,"area":"Europe","q":"Whose flag is 🇪🇸?","o":["Spain","Russia","Italy","Greece"],"a":[0],"s":1,"x":"🇪🇸 is the flag of Spain.","about":["spain"]},
{"id":"FL-005","lv":"ea","d":3,"area":"Europe","q":"Whose flag is 🇵🇹?","o":["Sweden","Portugal","Ireland","Ukraine"],"a":[1],"s":1,"x":"🇵🇹 is the flag of Portugal.","about":["portugal"]},
{"id":"FL-006","lv":"ea","d":3,"area":"Europe","q":"Whose flag is 🇳🇱?","o":["Netherlands","Hungary","Belgium","Finland"],"a":[0],"s":1,"x":"🇳🇱 is the flag of Netherlands.","about":["netherlands"]},
{"id":"FL-007","lv":"ea","d":3,"area":"Europe","q":"Whose flag is 🇧🇪?","o":["Belgium","Denmark","Finland","Netherlands"],"a":[0],"s":1,"x":"🇧🇪 is the flag of Belgium.","about":["belgium"]},
{"id":"FL-008","lv":"mi","d":4,"area":"Europe","q":"Whose flag is 🇨🇭?","o":["Estonia","Bulgaria","Switzerland","Croatia"],"a":[2],"s":1,"x":"🇨🇭 is the flag of Switzerland.","about":["switzerland"]},
{"id":"FL-009","lv":"ea","d":3,"area":"Europe","q":"Whose flag is 🇦🇹?","o":["Sweden","Poland","Austria","Ukraine"],"a":[2],"s":1,"x":"🇦🇹 is the flag of Austria.","about":["austria"]},
{"id":"FL-010","lv":"ea","d":3,"area":"Europe","q":"Whose flag is 🇩🇰?","o":["Denmark","Czech Republic","Ukraine","Hungary"],"a":[0],"s":1,"x":"🇩🇰 is the flag of Denmark.","about":["denmark"]},
{"id":"FL-011","lv":"ea","d":3,"area":"Europe","q":"Whose flag is 🇸🇪?","o":["Finland","Belgium","Sweden","Ireland"],"a":[2],"s":1,"x":"🇸🇪 is the flag of Sweden.","about":["sweden"]},
{"id":"FL-012","lv":"ea","d":3,"area":"Europe","q":"Whose flag is 🇳🇴?","o":["Norway","Poland","Portugal","Belgium"],"a":[0],"s":1,"x":"🇳🇴 is the flag of Norway.","about":["norway"]},
{"id":"FL-013","lv":"ea","d":3,"area":"Europe","q":"Whose flag is 🇫🇮?","o":["Ireland","Netherlands","Belgium","Finland"],"a":[3],"s":1,"x":"🇫🇮 is the flag of Finland.","about":["finland"]},
{"id":"FL-014","lv":"mi","d":4,"area":"Europe","q":"Whose flag is 🇮🇸?","o":["Lithuania","Iceland","Switzerland","Serbia"],"a":[1],"s":1,"x":"🇮🇸 is the flag of Iceland.","about":["iceland"]},
{"id":"FL-015","lv":"ea","d":3,"area":"Europe","q":"Whose flag is 🇮🇪?","o":["Portugal","Hungary","Ireland","Belgium"],"a":[2],"s":1,"x":"🇮🇪 is the flag of Ireland.","about":["ireland"]},
{"id":"FL-016","lv":"ea","d":2,"area":"Europe","q":"Whose flag is 🇬🇧?","o":["Russia","United Kingdom","France","Italy"],"a":[1],"s":1,"x":"🇬🇧 is the flag of United Kingdom.","about":["uk"]},
{"id":"FL-017","lv":"ea","d":3,"area":"Europe","q":"Whose flag is 🇵🇱?","o":["Sweden","Finland","Denmark","Poland"],"a":[3],"s":1,"x":"🇵🇱 is the flag of Poland.","about":["poland"]},
{"id":"FL-018","lv":"ea","d":3,"area":"Europe","q":"Whose flag is 🇨🇿?","o":["Austria","Belgium","Ireland","Czech Republic"],"a":[3],"s":1,"x":"🇨🇿 is the flag of Czech Republic.","about":["czech-republic"]},
{"id":"FL-019","lv":"mi","d":5,"area":"Europe","q":"Whose flag is 🇸🇰?","o":["Albania","Slovakia","Slovenia","Cyprus"],"a":[1],"s":1,"x":"🇸🇰 is the flag of Slovakia.","about":["slovakia"]},
{"id":"FL-020","lv":"ea","d":3,"area":"Europe","q":"Whose flag is 🇭🇺?","o":["Ireland","Ukraine","Portugal","Hungary"],"a":[3],"s":1,"x":"🇭🇺 is the flag of Hungary.","about":["hungary"]},
{"id":"FL-021","lv":"mi","d":4,"area":"Europe","q":"Whose flag is 🇷🇴?","o":["Iceland","Romania","Estonia","Croatia"],"a":[1],"s":1,"x":"🇷🇴 is the flag of Romania.","about":["romania"]},
{"id":"FL-022","lv":"mi","d":4,"area":"Europe","q":"Whose flag is 🇧🇬?","o":["Bulgaria","Lithuania","Croatia","Latvia"],"a":[0],"s":1,"x":"🇧🇬 is the flag of Bulgaria.","about":["bulgaria"]},
{"id":"FL-023","lv":"ea","d":2,"area":"Europe","q":"Whose flag is 🇬🇷?","o":["Greece","Italy","United Kingdom","Spain"],"a":[0],"s":1,"x":"🇬🇷 is the flag of Greece.","about":["greece"]},
{"id":"FL-024","lv":"mi","d":4,"area":"Europe","q":"Whose flag is 🇭🇷?","o":["Luxembourg","Belarus","Croatia","Serbia"],"a":[2],"s":1,"x":"🇭🇷 is the flag of Croatia.","about":["croatia"]},
{"id":"FL-025","lv":"mi","d":5,"area":"Europe","q":"Whose flag is 🇸🇮?","o":["Vatican City","Slovenia","Cyprus","Albania"],"a":[1],"s":1,"x":"🇸🇮 is the flag of Slovenia.","about":["slovenia"]},
{"id":"FL-026","lv":"mi","d":4,"area":"Europe","q":"Whose flag is 🇷🇸?","o":["Serbia","Croatia","Lithuania","Latvia"],"a":[0],"s":1,"x":"🇷🇸 is the flag of Serbia.","about":["serbia"]},
{"id":"FL-027","lv":"mi","d":5,"area":"Europe","q":"Whose flag is 🇧🇦?","o":["Slovakia","Monaco","Slovenia","Bosnia and Herzegovina"],"a":[3],"s":1,"x":"🇧🇦 is the flag of Bosnia and Herzegovina.","about":["bosnia-and-herzegovina"]},
{"id":"FL-028","lv":"ha","d":7,"area":"Europe","q":"Whose flag is 🇲🇪?","o":["Kosovo","Andorra","Montenegro","Liechtenstein"],"a":[2],"s":1,"x":"🇲🇪 is the flag of Montenegro.","about":["montenegro"]},
{"id":"FL-029","lv":"ha","d":6,"area":"Europe","q":"Whose flag is 🇲🇰?","o":["Malta","Montenegro","North Macedonia","San Marino"],"a":[2],"s":1,"x":"🇲🇰 is the flag of North Macedonia.","about":["north-macedonia"]},
{"id":"FL-030","lv":"mi","d":5,"area":"Europe","q":"Whose flag is 🇦🇱?","o":["Albania","Vatican City","Bosnia and Herzegovina","Cyprus"],"a":[0],"s":1,"x":"🇦🇱 is the flag of Albania.","about":["albania"]},
{"id":"FL-031","lv":"ha","d":7,"area":"Europe","q":"Whose flag is 🇽🇰?","o":["Kosovo","Moldova","Andorra","Montenegro"],"a":[0],"s":1,"x":"🇽🇰 is the flag of Kosovo.","about":["kosovo"]},
{"id":"FL-032","lv":"mi","d":4,"area":"Europe","q":"Whose flag is 🇪🇪?","o":["Serbia","Croatia","Switzerland","Estonia"],"a":[3],"s":1,"x":"🇪🇪 is the flag of Estonia.","about":["estonia"]},
{"id":"FL-033","lv":"mi","d":4,"area":"Europe","q":"Whose flag is 🇱🇻?","o":["Latvia","Switzerland","Estonia","Iceland"],"a":[0],"s":1,"x":"🇱🇻 is the flag of Latvia.","about":["latvia"]},
{"id":"FL-034","lv":"mi","d":4,"area":"Europe","q":"Whose flag is 🇱🇹?","o":["Latvia","Iceland","Lithuania","Luxembourg"],"a":[2],"s":1,"x":"🇱🇹 is the flag of Lithuania.","about":["lithuania"]},
{"id":"FL-035","lv":"mi","d":4,"area":"Europe","q":"Whose flag is 🇧🇾?","o":["Estonia","Belarus","Romania","Latvia"],"a":[1],"s":1,"x":"🇧🇾 is the flag of Belarus.","about":["belarus"]},
{"id":"FL-036","lv":"ea","d":3,"area":"Europe","q":"Whose flag is 🇺🇦?","o":["Portugal","Ukraine","Poland","Ireland"],"a":[1],"s":1,"x":"🇺🇦 is the flag of Ukraine.","about":["ukraine"]},
{"id":"FL-037","lv":"ha","d":7,"area":"Europe","q":"Whose flag is 🇲🇩?","o":["Moldova","Andorra","Montenegro","Kosovo"],"a":[0],"s":1,"x":"🇲🇩 is the flag of Moldova.","about":["moldova"]},
{"id":"FL-038","lv":"ea","d":2,"area":"Europe","q":"Whose flag is 🇷🇺?","o":["Spain","Greece","Russia","France"],"a":[2],"s":1,"x":"🇷🇺 is the flag of Russia.","about":["russia"]},
{"id":"FL-039","lv":"mi","d":4,"area":"Europe","q":"Whose flag is 🇱🇺?","o":["Iceland","Luxembourg","Bulgaria","Romania"],"a":[1],"s":1,"x":"🇱🇺 is the flag of Luxembourg.","about":["luxembourg"]},
{"id":"FL-040","lv":"ha","d":6,"area":"Europe","q":"Whose flag is 🇲🇹?","o":["North Macedonia","Montenegro","Malta","San Marino"],"a":[2],"s":1,"x":"🇲🇹 is the flag of Malta.","about":["malta"]},
{"id":"FL-041","lv":"mi","d":5,"area":"Europe","q":"Whose flag is 🇨🇾?","o":["Slovenia","Cyprus","Albania","Bosnia and Herzegovina"],"a":[1],"s":1,"x":"🇨🇾 is the flag of Cyprus.","about":["cyprus"]},
{"id":"FL-042","lv":"ha","d":7,"area":"Europe","q":"Whose flag is 🇦🇩?","o":["Moldova","Liechtenstein","Andorra","Kosovo"],"a":[2],"s":1,"x":"🇦🇩 is the flag of Andorra.","about":["andorra"]},
{"id":"FL-043","lv":"mi","d":5,"area":"Europe","q":"Whose flag is 🇲🇨?","o":["Bosnia and Herzegovina","Monaco","Slovakia","Albania"],"a":[1],"s":1,"x":"🇲🇨 is the flag of Monaco.","about":["monaco"]},
{"id":"FL-044","lv":"ha","d":7,"area":"Europe","q":"Whose flag is 🇱🇮?","o":["Montenegro","Moldova","Kosovo","Liechtenstein"],"a":[3],"s":1,"x":"🇱🇮 is the flag of Liechtenstein.","about":["liechtenstein"]},
{"id":"FL-045","lv":"ha","d":6,"area":"Europe","q":"Whose flag is 🇸🇲?","o":["Montenegro","Malta","North Macedonia","San Marino"],"a":[3],"s":1,"x":"🇸🇲 is the flag of San Marino.","about":["san-marino"]},
{"id":"FL-046","lv":"ea","d":3,"area":"Asia","q":"Whose flag is 🇹🇷?","o":["Turkey","Vietnam","Philippines","Afghanistan"],"a":[0],"s":1,"x":"🇹🇷 is the flag of Turkey.","about":["turkey"]},
{"id":"FL-047","lv":"mi","d":5,"area":"Asia","q":"Whose flag is 🇬🇪?","o":["Armenia","Uzbekistan","Georgia","Mongolia"],"a":[2],"s":1,"x":"🇬🇪 is the flag of Georgia.","about":["georgia"]},
{"id":"FL-048","lv":"mi","d":5,"area":"Asia","q":"Whose flag is 🇦🇲?","o":["Uzbekistan","Armenia","Mongolia","Georgia"],"a":[1],"s":1,"x":"🇦🇲 is the flag of Armenia.","about":["armenia"]},
{"id":"FL-049","lv":"mi","d":4,"area":"Asia","q":"Whose flag is 🇦🇿?","o":["Kazakhstan","Azerbaijan","Nepal","Cambodia"],"a":[1],"s":1,"x":"🇦🇿 is the flag of Azerbaijan.","about":["azerbaijan"]},
{"id":"FL-050","lv":"mi","d":4,"area":"Asia","q":"Whose flag is 🇰🇿?","o":["Nepal","Azerbaijan","Kazakhstan","Bangladesh"],"a":[2],"s":1,"x":"🇰🇿 is the flag of Kazakhstan.","about":["kazakhstan"]},
{"id":"FL-051","lv":"mi","d":5,"area":"Asia","q":"Whose flag is 🇺🇿?","o":["Uzbekistan","Georgia","Mongolia","Armenia"],"a":[0],"s":1,"x":"🇺🇿 is the flag of Uzbekistan.","about":["uzbekistan"]},
{"id":"FL-052","lv":"ha","d":7,"area":"Asia","q":"Whose flag is 🇹🇲?","o":["Brunei","Kyrgyzstan","Tajikistan","Turkmenistan"],"a":[3],"s":1,"x":"🇹🇲 is the flag of Turkmenistan.","about":["turkmenistan"]},
{"id":"FL-053","lv":"ha","d":7,"area":"Asia","q":"Whose flag is 🇰🇬?","o":["Kyrgyzstan","Tajikistan","Turkmenistan","Brunei"],"a":[0],"s":1,"x":"🇰🇬 is the flag of Kyrgyzstan.","about":["kyrgyzstan"]},
{"id":"FL-054","lv":"ha","d":7,"area":"Asia","q":"Whose flag is 🇹🇯?","o":["Tajikistan","Turkmenistan","Brunei","Bhutan"],"a":[0],"s":1,"x":"🇹🇯 is the flag of Tajikistan.","about":["tajikistan"]},
{"id":"FL-055","lv":"ea","d":3,"area":"Asia","q":"Whose flag is 🇦🇫?","o":["Malaysia","Turkey","Vietnam","Afghanistan"],"a":[3],"s":1,"x":"🇦🇫 is the flag of Afghanistan.","about":["afghanistan"]},
{"id":"FL-056","lv":"ea","d":3,"area":"Asia","q":"Whose flag is 🇵🇰?","o":["Vietnam","Pakistan","Turkey","Indonesia"],"a":[1],"s":1,"x":"🇵🇰 is the flag of Pakistan.","about":["pakistan"]},
{"id":"FL-057","lv":"ea","d":2,"area":"Asia","q":"Whose flag is 🇮🇳?","o":["India","China","Thailand","Japan"],"a":[0],"s":1,"x":"🇮🇳 is the flag of India.","about":["india"]},
{"id":"FL-058","lv":"mi","d":4,"area":"Asia","q":"Whose flag is 🇳🇵?","o":["Azerbaijan","Bangladesh","Nepal","Cambodia"],"a":[2],"s":1,"x":"🇳🇵 is the flag of Nepal.","about":["nepal"]},
{"id":"FL-059","lv":"ha","d":7,"area":"Asia","q":"Whose flag is 🇧🇹?","o":["Brunei","Kyrgyzstan","Bhutan","Tajikistan"],"a":[2],"s":1,"x":"🇧🇹 is the flag of Bhutan.","about":["bhutan"]},
{"id":"FL-060","lv":"mi","d":4,"area":"Asia","q":"Whose flag is 🇧🇩?","o":["Bangladesh","Kazakhstan","Azerbaijan","Nepal"],"a":[0],"s":1,"x":"🇧🇩 is the flag of Bangladesh.","about":["bangladesh"]},
{"id":"FL-061","lv":"ha","d":8,"area":"Asia","q":"Whose flag is 🇱🇰?","o":["Sri Lanka","East Timor","Tajikistan","Bhutan"],"a":[0],"s":1,"x":"🇱🇰 is the flag of Sri Lanka.","about":["sri-lanka"]},
{"id":"FL-062","lv":"ha","d":6,"area":"Asia","q":"Whose flag is 🇲🇻?","o":["Myanmar","Brunei","Maldives","Laos"],"a":[2],"s":1,"x":"🇲🇻 is the flag of Maldives.","about":["maldives"]},
{"id":"FL-063","lv":"ea","d":2,"area":"Asia","q":"Whose flag is 🇨🇳?","o":["India","South Korea","Singapore","China"],"a":[3],"s":1,"x":"🇨🇳 is the flag of China.","about":["china"]},
{"id":"FL-064","lv":"mi","d":5,"area":"Asia","q":"Whose flag is 🇲🇳?","o":["Mongolia","Uzbekistan","Armenia","Georgia"],"a":[0],"s":1,"x":"🇲🇳 is the flag of Mongolia.","about":["mongolia"]},
{"id":"FL-065","lv":"ea","d":3,"area":"Asia","q":"Whose flag is 🇰🇵?","o":["Philippines","Malaysia","Vietnam","North Korea"],"a":[3],"s":1,"x":"🇰🇵 is the flag of North Korea.","about":["north-korea"]},
{"id":"FL-066","lv":"ea","d":2,"area":"Asia","q":"Whose flag is 🇰🇷?","o":["India","Japan","South Korea","China"],"a":[2],"s":1,"x":"🇰🇷 is the flag of South Korea.","about":["south-korea"]},
{"id":"FL-067","lv":"ea","d":2,"area":"Asia","q":"Whose flag is 🇯🇵?","o":["South Korea","Japan","Singapore","China"],"a":[1],"s":1,"x":"🇯🇵 is the flag of Japan.","about":["japan"]},
{"id":"FL-068","lv":"ea","d":3,"area":"Asia","q":"Whose flag is 🇹🇼?","o":["Taiwan","Indonesia","Vietnam","Turkey"],"a":[0],"s":1,"x":"🇹🇼 is the flag of Taiwan.","about":["taiwan"]},
{"id":"FL-069","lv":"ea","d":3,"area":"Asia","q":"Whose flag is 🇻🇳?","o":["North Korea","Pakistan","Vietnam","Taiwan"],"a":[2],"s":1,"x":"🇻🇳 is the flag of Vietnam.","about":["vietnam"]},
{"id":"FL-070","lv":"ha","d":6,"area":"Asia","q":"Whose flag is 🇱🇦?","o":["Maldives","Myanmar","Laos","Mongolia"],"a":[2],"s":1,"x":"🇱🇦 is the flag of Laos.","about":["laos"]},
{"id":"FL-071","lv":"mi","d":4,"area":"Asia","q":"Whose flag is 🇰🇭?","o":["Kazakhstan","Bangladesh","Azerbaijan","Cambodia"],"a":[3],"s":1,"x":"🇰🇭 is the flag of Cambodia.","about":["cambodia"]},
{"id":"FL-072","lv":"ea","d":2,"area":"Asia","q":"Whose flag is 🇹🇭?","o":["China","Thailand","Japan","South Korea"],"a":[1],"s":1,"x":"🇹🇭 is the flag of Thailand.","about":["thailand"]},
{"id":"FL-073","lv":"ha","d":6,"area":"Asia","q":"Whose flag is 🇲🇲?","o":["Bhutan","Myanmar","Maldives","Laos"],"a":[1],"s":1,"x":"🇲🇲 is the flag of Myanmar.","about":["myanmar"]},
{"id":"FL-074","lv":"ea","d":3,"area":"Asia","q":"Whose flag is 🇲🇾?","o":["Malaysia","Vietnam","Afghanistan","Philippines"],"a":[0],"s":1,"x":"🇲🇾 is the flag of Malaysia.","about":["malaysia"]},
{"id":"FL-075","lv":"ea","d":2,"area":"Asia","q":"Whose flag is 🇸🇬?","o":["Singapore","Japan","South Korea","Thailand"],"a":[0],"s":1,"x":"🇸🇬 is the flag of Singapore.","about":["singapore"]},
{"id":"FL-076","lv":"ea","d":3,"area":"Asia","q":"Whose flag is 🇮🇩?","o":["Vietnam","North Korea","Malaysia","Indonesia"],"a":[3],"s":1,"x":"🇮🇩 is the flag of Indonesia.","about":["indonesia"]},
{"id":"FL-077","lv":"ha","d":7,"area":"Asia","q":"Whose flag is 🇧🇳?","o":["Bhutan","Tajikistan","Kyrgyzstan","Brunei"],"a":[3],"s":1,"x":"🇧🇳 is the flag of Brunei.","about":["brunei"]},
{"id":"FL-078","lv":"ea","d":3,"area":"Asia","q":"Whose flag is 🇵🇭?","o":["Turkey","Philippines","Indonesia","Vietnam"],"a":[1],"s":1,"x":"🇵🇭 is the flag of Philippines.","about":["philippines"]},
{"id":"FL-079","lv":"ha","d":8,"area":"Asia","q":"Whose flag is 🇹🇱?","o":["Turkmenistan","East Timor","Sri Lanka","Brunei"],"a":[1],"s":1,"x":"🇹🇱 is the flag of East Timor.","about":["east-timor"]},
{"id":"FL-080","lv":"ea","d":3,"area":"Middle East","q":"Whose flag is 🇮🇷?","o":["Iran","United Arab Emirates","Syria","Saudi Arabia"],"a":[0],"s":1,"x":"🇮🇷 is the flag of Iran.","about":["iran"]},
{"id":"FL-081","lv":"ea","d":3,"area":"Middle East","q":"Whose flag is 🇮🇶?","o":["Qatar","Saudi Arabia","Israel","Iraq"],"a":[3],"s":1,"x":"🇮🇶 is the flag of Iraq.","about":["iraq"]},
{"id":"FL-082","lv":"ea","d":3,"area":"Middle East","q":"Whose flag is 🇸🇾?","o":["Syria","Iran","United Arab Emirates","Israel"],"a":[0],"s":1,"x":"🇸🇾 is the flag of Syria.","about":["syria"]},
{"id":"FL-083","lv":"mi","d":4,"area":"Middle East","q":"Whose flag is 🇱🇧?","o":["Yemen","Kuwait","Lebanon","Jordan"],"a":[2],"s":1,"x":"🇱🇧 is the flag of Lebanon.","about":["lebanon"]},
{"id":"FL-084","lv":"ea","d":3,"area":"Middle East","q":"Whose flag is 🇮🇱?","o":["Israel","Qatar","Iran","Syria"],"a":[0],"s":1,"x":"🇮🇱 is the flag of Israel.","about":["israel"]},
{"id":"FL-085","lv":"mi","d":4,"area":"Middle East","q":"Whose flag is 🇯🇴?","o":["Lebanon","Jordan","Kuwait","Israel"],"a":[1],"s":1,"x":"🇯🇴 is the flag of Jordan.","about":["jordan"]},
{"id":"FL-086","lv":"ea","d":3,"area":"Middle East","q":"Whose flag is 🇸🇦?","o":["United Arab Emirates","Israel","Syria","Saudi Arabia"],"a":[3],"s":1,"x":"🇸🇦 is the flag of Saudi Arabia.","about":["saudi-arabia"]},
{"id":"FL-087","lv":"mi","d":5,"area":"Middle East","q":"Whose flag is 🇾🇪?","o":["Bahrain","Yemen","Palestine","Oman"],"a":[1],"s":1,"x":"🇾🇪 is the flag of Yemen.","about":["yemen"]},
{"id":"FL-088","lv":"mi","d":5,"area":"Middle East","q":"Whose flag is 🇴🇲?","o":["Bahrain","Palestine","Oman","Yemen"],"a":[2],"s":1,"x":"🇴🇲 is the flag of Oman.","about":["oman"]},
{"id":"FL-089","lv":"ea","d":3,"area":"Middle East","q":"Whose flag is 🇦🇪?","o":["United Arab Emirates","Saudi Arabia","Syria","Iraq"],"a":[0],"s":1,"x":"🇦🇪 is the flag of United Arab Emirates.","about":["uae"]},
{"id":"FL-090","lv":"ea","d":3,"area":"Middle East","q":"Whose flag is 🇶🇦?","o":["Iraq","Qatar","United Arab Emirates","Israel"],"a":[1],"s":1,"x":"🇶🇦 is the flag of Qatar.","about":["qatar"]},
{"id":"FL-091","lv":"mi","d":5,"area":"Middle East","q":"Whose flag is 🇧🇭?","o":["Oman","Palestine","Bahrain","Yemen"],"a":[2],"s":1,"x":"🇧🇭 is the flag of Bahrain.","about":["bahrain"]},
{"id":"FL-092","lv":"mi","d":4,"area":"Middle East","q":"Whose flag is 🇰🇼?","o":["Jordan","United Arab Emirates","Kuwait","Lebanon"],"a":[2],"s":1,"x":"🇰🇼 is the flag of Kuwait.","about":["kuwait"]},
{"id":"FL-093","lv":"ea","d":2,"area":"Africa","q":"Whose flag is 🇪🇬?","o":["South Africa","Kenya","Ethiopia","Egypt"],"a":[3],"s":1,"x":"🇪🇬 is the flag of Egypt.","about":["egypt"]},
{"id":"FL-094","lv":"mi","d":4,"area":"Africa","q":"Whose flag is 🇱🇾?","o":["Sudan","Uganda","Libya","Democratic Republic of the Congo"],"a":[2],"s":1,"x":"🇱🇾 is the flag of Libya.","about":["libya"]},
{"id":"FL-095","lv":"ea","d":3,"area":"Africa","q":"Whose flag is 🇹🇳?","o":["South Africa","Tunisia","Ghana","Algeria"],"a":[1],"s":1,"x":"🇹🇳 is the flag of Tunisia.","about":["tunisia"]},
{"id":"FL-096","lv":"ea","d":3,"area":"Africa","q":"Whose flag is 🇩🇿?","o":["Tunisia","Ethiopia","Algeria","Ghana"],"a":[2],"s":1,"x":"🇩🇿 is the flag of Algeria.","about":["algeria"]},
{"id":"FL-097","lv":"mi","d":4,"area":"Africa","q":"Whose flag is 🇲🇦?","o":["Sudan","Angola","Senegal","Morocco"],"a":[3],"s":1,"x":"🇲🇦 is the flag of Morocco.","about":["morocco"]},
{"id":"FL-098","lv":"ha","d":7,"area":"Africa","q":"Whose flag is 🇲🇷?","o":["Togo","Mauritania","Seychelles","Côte d'Ivoire"],"a":[1],"s":1,"x":"🇲🇷 is the flag of Mauritania.","about":["mauritania"]},
{"id":"FL-099","lv":"ha","d":6,"area":"Africa","q":"Whose flag is 🇲🇱?","o":["Botswana","Djibouti","Mali","Mauritius"],"a":[2],"s":1,"x":"🇲🇱 is the flag of Mali.","about":["mali"]},
{"id":"FL-100","lv":"ha","d":7,"area":"Africa","q":"Whose flag is 🇳🇪?","o":["Niger","Gabon","South Sudan","Mauritania"],"a":[0],"s":1,"x":"🇳🇪 is the flag of Niger.","about":["niger"]},
{"id":"FL-101","lv":"ha","d":7,"area":"Africa","q":"Whose flag is 🇹🇩?","o":["Chad","Malawi","Guinea","Gabon"],"a":[0],"s":1,"x":"🇹🇩 is the flag of Chad.","about":["chad"]},
{"id":"FL-102","lv":"mi","d":4,"area":"Africa","q":"Whose flag is 🇸🇩?","o":["Somalia","Zimbabwe","Democratic Republic of the Congo","Sudan"],"a":[3],"s":1,"x":"🇸🇩 is the flag of Sudan.","about":["sudan"]},
{"id":"FL-103","lv":"ha","d":7,"area":"Africa","q":"Whose flag is 🇸🇸?","o":["Gambia","Tanzania","Eritrea","South Sudan"],"a":[3],"s":1,"x":"🇸🇸 is the flag of South Sudan.","about":["south-sudan"]},
{"id":"FL-104","lv":"ha","d":7,"area":"Africa","q":"Whose flag is 🇪🇷?","o":["Togo","Eritrea","Tanzania","Niger"],"a":[1],"s":1,"x":"🇪🇷 is the flag of Eritrea.","about":["eritrea"]},
{"id":"FL-105","lv":"ea","d":3,"area":"Africa","q":"Whose flag is 🇪🇹?","o":["South Africa","Ethiopia","Algeria","Tunisia"],"a":[1],"s":1,"x":"🇪🇹 is the flag of Ethiopia.","about":["ethiopia"]},
{"id":"FL-106","lv":"ha","d":6,"area":"Africa","q":"Whose flag is 🇩🇯?","o":["Liberia","Sierra Leone","Mali","Djibouti"],"a":[3],"s":1,"x":"🇩🇯 is the flag of Djibouti.","about":["djibouti"]},
{"id":"FL-107","lv":"mi","d":4,"area":"Africa","q":"Whose flag is 🇸🇴?","o":["Somalia","Zimbabwe","Nigeria","Morocco"],"a":[0],"s":1,"x":"🇸🇴 is the flag of Somalia.","about":["somalia"]},
{"id":"FL-108","lv":"ea","d":2,"area":"Africa","q":"Whose flag is 🇰🇪?","o":["Algeria","Egypt","Kenya","Ethiopia"],"a":[2],"s":1,"x":"🇰🇪 is the flag of Kenya.","about":["kenya"]},
{"id":"FL-109","lv":"mi","d":4,"area":"Africa","q":"Whose flag is 🇺🇬?","o":["Morocco","Uganda","Sudan","Zimbabwe"],"a":[1],"s":1,"x":"🇺🇬 is the flag of Uganda.","about":["uganda"]},
{"id":"FL-110","lv":"mi","d":5,"area":"Africa","q":"Whose flag is 🇷🇼?","o":["Rwanda","Namibia","Zambia","Mozambique"],"a":[0],"s":1,"x":"🇷🇼 is the flag of Rwanda.","about":["rwanda"]},
{"id":"FL-111","lv":"ha","d":9,"area":"Africa","q":"Whose flag is 🇧🇮?","o":["Burundi","Comoros","Equatorial Guinea","Lesotho"],"a":[0],"s":1,"x":"🇧🇮 is the flag of Burundi.","about":["burundi"]},
{"id":"FL-112","lv":"ha","d":7,"area":"Africa","q":"Whose flag is 🇹🇿?","o":["Gambia","Chad","Tanzania","Mauritania"],"a":[2],"s":1,"x":"🇹🇿 is the flag of Tanzania.","about":["tanzania"]},
{"id":"FL-113","lv":"mi","d":4,"area":"Africa","q":"Whose flag is 🇸🇳?","o":["Senegal","Libya","Morocco","Sudan"],"a":[0],"s":1,"x":"🇸🇳 is the flag of Senegal.","about":["senegal"]},
{"id":"FL-114","lv":"ha","d":7,"area":"Africa","q":"Whose flag is 🇬🇲?","o":["Gabon","Gambia","South Sudan","Côte d'Ivoire"],"a":[1],"s":1,"x":"🇬🇲 is the flag of Gambia.","about":["gambia"]},
{"id":"FL-115","lv":"ha","d":7,"area":"Africa","q":"Whose flag is 🇬🇳?","o":["Eritrea","Guinea","Seychelles","Gambia"],"a":[1],"s":1,"x":"🇬🇳 is the flag of Guinea.","about":["guinea"]},
{"id":"FL-116","lv":"ha","d":8,"area":"Africa","q":"Whose flag is 🇬🇼?","o":["Lesotho","Benin","Guinea-Bissau","Central African Republic"],"a":[2],"s":1,"x":"🇬🇼 is the flag of Guinea-Bissau.","about":["guinea-bissau"]},
{"id":"FL-117","lv":"ha","d":6,"area":"Africa","q":"Whose flag is 🇸🇱?","o":["Mauritius","Burkina Faso","Sierra Leone","Botswana"],"a":[2],"s":1,"x":"🇸🇱 is the flag of Sierra Leone.","about":["sierra-leone"]},
{"id":"FL-118","lv":"ha","d":6,"area":"Africa","q":"Whose flag is 🇱🇷?","o":["Burkina Faso","Liberia","Cameroon","Mauritius"],"a":[1],"s":1,"x":"🇱🇷 is the flag of Liberia.","about":["liberia"]},
{"id":"FL-119","lv":"ha","d":7,"area":"Africa","q":"Whose flag is 🇨🇮?","o":["Côte d'Ivoire","Niger","Tanzania","Chad"],"a":[0],"s":1,"x":"🇨🇮 is the flag of Côte d'Ivoire.","about":["ivory-coast"]},
{"id":"FL-120","lv":"ea","d":3,"area":"Africa","q":"Whose flag is 🇬🇭?","o":["Ethiopia","South Africa","Ghana","Tunisia"],"a":[2],"s":1,"x":"🇬🇭 is the flag of Ghana.","about":["ghana"]},
{"id":"FL-121","lv":"ha","d":7,"area":"Africa","q":"Whose flag is 🇹🇬?","o":["Togo","Eritrea","Mauritania","Côte d'Ivoire"],"a":[0],"s":1,"x":"🇹🇬 is the flag of Togo.","about":["togo"]},
{"id":"FL-122","lv":"ha","d":8,"area":"Africa","q":"Whose flag is 🇧🇯?","o":["Guinea-Bissau","Benin","São Tomé and Príncipe","Eswatini"],"a":[1],"s":1,"x":"🇧🇯 is the flag of Benin.","about":["benin"]},
{"id":"FL-123","lv":"ha","d":6,"area":"Africa","q":"Whose flag is 🇧🇫?","o":["Cameroon","Burkina Faso","Sierra Leone","Mauritius"],"a":[1],"s":1,"x":"🇧🇫 is the flag of Burkina Faso.","about":["burkina-faso"]},
{"id":"FL-124","lv":"mi","d":4,"area":"Africa","q":"Whose flag is 🇳🇬?","o":["Libya","Democratic Republic of the Congo","Zimbabwe","Nigeria"],"a":[3],"s":1,"x":"🇳🇬 is the flag of Nigeria.","about":["nigeria"]},
{"id":"FL-125","lv":"ha","d":6,"area":"Africa","q":"Whose flag is 🇨🇲?","o":["Republic of the Congo","Sierra Leone","Cameroon","Liberia"],"a":[2],"s":1,"x":"🇨🇲 is the flag of Cameroon.","about":["cameroon"]},
{"id":"FL-126","lv":"ha","d":8,"area":"Africa","q":"Whose flag is 🇨🇫?","o":["Central African Republic","Equatorial Guinea","Lesotho","Benin"],"a":[0],"s":1,"x":"🇨🇫 is the flag of Central African Republic.","about":["central-african-republic"]},
{"id":"FL-127","lv":"ha","d":7,"area":"Africa","q":"Whose flag is 🇬🇦?","o":["Gambia","Malawi","Gabon","Tanzania"],"a":[2],"s":1,"x":"🇬🇦 is the flag of Gabon.","about":["gabon"]},
{"id":"FL-128","lv":"ha","d":8,"area":"Africa","q":"Whose flag is 🇬🇶?","o":["Eswatini","Benin","Comoros","Equatorial Guinea"],"a":[3],"s":1,"x":"🇬🇶 is the flag of Equatorial Guinea.","about":["equatorial-guinea"]},
{"id":"FL-129","lv":"ha","d":6,"area":"Africa","q":"Whose flag is 🇨🇬?","o":["Republic of the Congo","Sierra Leone","Botswana","Mali"],"a":[0],"s":1,"x":"🇨🇬 is the flag of Republic of the Congo.","about":["republic-of-the-congo"]},
{"id":"FL-130","lv":"mi","d":4,"area":"Africa","q":"Whose flag is 🇨🇩?","o":["Libya","Nigeria","Democratic Republic of the Congo","Sudan"],"a":[2],"s":1,"x":"🇨🇩 is the flag of Democratic Republic of the Congo.","about":["dr-congo"]},
{"id":"FL-131","lv":"mi","d":4,"area":"Africa","q":"Whose flag is 🇦🇴?","o":["Libya","Angola","Democratic Republic of the Congo","Zimbabwe"],"a":[1],"s":1,"x":"🇦🇴 is the flag of Angola.","about":["angola"]},
{"id":"FL-132","lv":"mi","d":5,"area":"Africa","q":"Whose flag is 🇿🇲?","o":["Rwanda","Zambia","Namibia","Madagascar"],"a":[1],"s":1,"x":"🇿🇲 is the flag of Zambia.","about":["zambia"]},
{"id":"FL-133","lv":"mi","d":4,"area":"Africa","q":"Whose flag is 🇿🇼?","o":["Libya","Democratic Republic of the Congo","Sudan","Zimbabwe"],"a":[3],"s":1,"x":"🇿🇼 is the flag of Zimbabwe.","about":["zimbabwe"]},
{"id":"FL-134","lv":"mi","d":5,"area":"Africa","q":"Whose flag is 🇲🇿?","o":["Rwanda","Namibia","Madagascar","Mozambique"],"a":[3],"s":1,"x":"🇲🇿 is the flag of Mozambique.","about":["mozambique"]},
{"id":"FL-135","lv":"ha","d":7,"area":"Africa","q":"Whose flag is 🇲🇼?","o":["South Sudan","Malawi","Gabon","Gambia"],"a":[1],"s":1,"x":"🇲🇼 is the flag of Malawi.","about":["malawi"]},
{"id":"FL-136","lv":"mi","d":5,"area":"Africa","q":"Whose flag is 🇲🇬?","o":["Zambia","Madagascar","Mozambique","Rwanda"],"a":[1],"s":1,"x":"🇲🇬 is the flag of Madagascar.","about":["madagascar"]},
{"id":"FL-137","lv":"mi","d":5,"area":"Africa","q":"Whose flag is 🇳🇦?","o":["Zambia","Madagascar","Mozambique","Namibia"],"a":[3],"s":1,"x":"🇳🇦 is the flag of Namibia.","about":["namibia"]},
{"id":"FL-138","lv":"ha","d":6,"area":"Africa","q":"Whose flag is 🇧🇼?","o":["Mali","Burkina Faso","Botswana","Cameroon"],"a":[2],"s":1,"x":"🇧🇼 is the flag of Botswana.","about":["botswana"]},
{"id":"FL-139","lv":"ea","d":3,"area":"Africa","q":"Whose flag is 🇿🇦?","o":["South Africa","Ghana","Algeria","Tunisia"],"a":[0],"s":1,"x":"🇿🇦 is the flag of South Africa.","about":["south-africa"]},
{"id":"FL-140","lv":"ha","d":8,"area":"Africa","q":"Whose flag is 🇱🇸?","o":["Comoros","Central African Republic","São Tomé and Príncipe","Lesotho"],"a":[3],"s":1,"x":"🇱🇸 is the flag of Lesotho.","about":["lesotho"]},
{"id":"FL-141","lv":"ha","d":8,"area":"Africa","q":"Whose flag is 🇸🇿?","o":["Comoros","Central African Republic","Eswatini","Guinea-Bissau"],"a":[2],"s":1,"x":"🇸🇿 is the flag of Eswatini.","about":["eswatini"]},
{"id":"FL-142","lv":"ha","d":6,"area":"Africa","q":"Whose flag is 🇲🇺?","o":["Mauritius","Burkina Faso","Cameroon","Mali"],"a":[0],"s":1,"x":"🇲🇺 is the flag of Mauritius.","about":["mauritius"]},
{"id":"FL-143","lv":"ha","d":7,"area":"Africa","q":"Whose flag is 🇸🇨?","o":["Seychelles","Chad","Cape Verde","Malawi"],"a":[0],"s":1,"x":"🇸🇨 is the flag of Seychelles.","about":["seychelles"]},
{"id":"FL-144","lv":"ha","d":7,"area":"Africa","q":"Whose flag is 🇨🇻?","o":["Cape Verde","Eritrea","Mauritania","Côte d'Ivoire"],"a":[0],"s":1,"x":"🇨🇻 is the flag of Cape Verde.","about":["cape-verde"]},
{"id":"FL-145","lv":"ea","d":2,"area":"Americas","q":"Whose flag is 🇺🇸?","o":["Mexico","United States","Cuba","Chile"],"a":[1],"s":1,"x":"🇺🇸 is the flag of United States.","about":["united-states"]},
{"id":"FL-146","lv":"ea","d":3,"area":"Americas","q":"Whose flag is 🇨🇦?","o":["Panama","Venezuela","Ecuador","Canada"],"a":[3],"s":1,"x":"🇨🇦 is the flag of Canada.","about":["canada"]},
{"id":"FL-147","lv":"ea","d":2,"area":"Americas","q":"Whose flag is 🇲🇽?","o":["Mexico","Argentina","Chile","Cuba"],"a":[0],"s":1,"x":"🇲🇽 is the flag of Mexico.","about":["mexico"]},
{"id":"FL-148","lv":"mi","d":4,"area":"Americas","q":"Whose flag is 🇬🇹?","o":["Uruguay","Guatemala","Dominican Republic","Costa Rica"],"a":[1],"s":1,"x":"🇬🇹 is the flag of Guatemala.","about":["guatemala"]},
{"id":"FL-149","lv":"ha","d":8,"area":"Americas","q":"Whose flag is 🇧🇿?","o":["Saint Lucia","Antigua and Barbuda","Belize","Dominica"],"a":[2],"s":1,"x":"🇧🇿 is the flag of Belize.","about":["belize"]},
{"id":"FL-150","lv":"ha","d":6,"area":"Americas","q":"Whose flag is 🇭🇳?","o":["Trinidad and Tobago","Guyana","Honduras","Bolivia"],"a":[2],"s":1,"x":"🇭🇳 is the flag of Honduras.","about":["honduras"]},
{"id":"FL-151","lv":"mi","d":5,"area":"Americas","q":"Whose flag is 🇸🇻?","o":["Haiti","El Salvador","Paraguay","Bahamas"],"a":[1],"s":1,"x":"🇸🇻 is the flag of El Salvador.","about":["el-salvador"]},
{"id":"FL-152","lv":"mi","d":5,"area":"Americas","q":"Whose flag is 🇳🇮?","o":["El Salvador","Paraguay","Nicaragua","Bahamas"],"a":[2],"s":1,"x":"🇳🇮 is the flag of Nicaragua.","about":["nicaragua"]},
{"id":"FL-153","lv":"mi","d":4,"area":"Americas","q":"Whose flag is 🇨🇷?","o":["Jamaica","Dominican Republic","Costa Rica","Uruguay"],"a":[2],"s":1,"x":"🇨🇷 is the flag of Costa Rica.","about":["costa-rica"]},
{"id":"FL-154","lv":"ea","d":3,"area":"Americas","q":"Whose flag is 🇵🇦?","o":["Ecuador","Venezuela","Panama","Colombia"],"a":[2],"s":1,"x":"🇵🇦 is the flag of Panama.","about":["panama"]},
{"id":"FL-155","lv":"ea","d":2,"area":"Americas","q":"Whose flag is 🇨🇺?","o":["Mexico","Cuba","Peru","Brazil"],"a":[1],"s":1,"x":"🇨🇺 is the flag of Cuba.","about":["cuba"]},
{"id":"FL-156","lv":"mi","d":4,"area":"Americas","q":"Whose flag is 🇯🇲?","o":["Uruguay","Jamaica","Costa Rica","Guatemala"],"a":[1],"s":1,"x":"🇯🇲 is the flag of Jamaica.","about":["jamaica"]},
{"id":"FL-157","lv":"mi","d":5,"area":"Americas","q":"Whose flag is 🇭🇹?","o":["Bahamas","Nicaragua","Haiti","Paraguay"],"a":[2],"s":1,"x":"🇭🇹 is the flag of Haiti.","about":["haiti"]},
{"id":"FL-158","lv":"mi","d":4,"area":"Americas","q":"Whose flag is 🇩🇴?","o":["Dominican Republic","Jamaica","Uruguay","Guatemala"],"a":[0],"s":1,"x":"🇩🇴 is the flag of Dominican Republic.","about":["dominican-republic"]},
{"id":"FL-159","lv":"mi","d":5,"area":"Americas","q":"Whose flag is 🇧🇸?","o":["Bahamas","Nicaragua","El Salvador","Paraguay"],"a":[0],"s":1,"x":"🇧🇸 is the flag of Bahamas.","about":["bahamas"]},
{"id":"FL-160","lv":"ha","d":6,"area":"Americas","q":"Whose flag is 🇹🇹?","o":["Guyana","Bolivia","Trinidad and Tobago","Honduras"],"a":[2],"s":1,"x":"🇹🇹 is the flag of Trinidad and Tobago.","about":["trinidad-and-tobago"]},
{"id":"FL-161","lv":"ha","d":7,"area":"Americas","q":"Whose flag is 🇧🇧?","o":["Antigua and Barbuda","Dominica","Barbados","Suriname"],"a":[2],"s":1,"x":"🇧🇧 is the flag of Barbados.","about":["barbados"]},
{"id":"FL-162","lv":"ea","d":3,"area":"Americas","q":"Whose flag is 🇨🇴?","o":["Canada","Ecuador","Colombia","Panama"],"a":[2],"s":1,"x":"🇨🇴 is the flag of Colombia.","about":["colombia"]},
{"id":"FL-163","lv":"ea","d":3,"area":"Americas","q":"Whose flag is 🇻🇪?","o":["Venezuela","Colombia","Ecuador","Panama"],"a":[0],"s":1,"x":"🇻🇪 is the flag of Venezuela.","about":["venezuela"]},
{"id":"FL-164","lv":"ha","d":6,"area":"Americas","q":"Whose flag is 🇬🇾?","o":["Bolivia","Guyana","Trinidad and Tobago","Honduras"],"a":[1],"s":1,"x":"🇬🇾 is the flag of Guyana.","about":["guyana"]},
{"id":"FL-165","lv":"ha","d":7,"area":"Americas","q":"Whose flag is 🇸🇷?","o":["Barbados","Suriname","Trinidad and Tobago","Honduras"],"a":[1],"s":1,"x":"🇸🇷 is the flag of Suriname.","about":["suriname"]},
{"id":"FL-166","lv":"ea","d":3,"area":"Americas","q":"Whose flag is 🇪🇨?","o":["Venezuela","Canada","Ecuador","Colombia"],"a":[2],"s":1,"x":"🇪🇨 is the flag of Ecuador.","about":["ecuador"]},
{"id":"FL-167","lv":"ea","d":2,"area":"Americas","q":"Whose flag is 🇵🇪?","o":["Peru","Mexico","United States","Cuba"],"a":[0],"s":1,"x":"🇵🇪 is the flag of Peru.","about":["peru"]},
{"id":"FL-168","lv":"ha","d":6,"area":"Americas","q":"Whose flag is 🇧🇴?","o":["Trinidad and Tobago","Guyana","Honduras","Bolivia"],"a":[3],"s":1,"x":"🇧🇴 is the flag of Bolivia.","about":["bolivia"]},
{"id":"FL-169","lv":"ea","d":2,"area":"Americas","q":"Whose flag is 🇧🇷?","o":["United States","Mexico","Cuba","Brazil"],"a":[3],"s":1,"x":"🇧🇷 is the flag of Brazil.","about":["brazil"]},
{"id":"FL-170","lv":"mi","d":5,"area":"Americas","q":"Whose flag is 🇵🇾?","o":["El Salvador","Nicaragua","Bahamas","Paraguay"],"a":[3],"s":1,"x":"🇵🇾 is the flag of Paraguay.","about":["paraguay"]},
{"id":"FL-171","lv":"mi","d":4,"area":"Americas","q":"Whose flag is 🇺🇾?","o":["Jamaica","Dominican Republic","Costa Rica","Uruguay"],"a":[3],"s":1,"x":"🇺🇾 is the flag of Uruguay.","about":["uruguay"]},
{"id":"FL-172","lv":"ea","d":2,"area":"Americas","q":"Whose flag is 🇨🇱?","o":["Chile","Brazil","Cuba","United States"],"a":[0],"s":1,"x":"🇨🇱 is the flag of Chile.","about":["chile"]},
{"id":"FL-173","lv":"ea","d":2,"area":"Americas","q":"Whose flag is 🇦🇷?","o":["Chile","Argentina","Peru","Mexico"],"a":[1],"s":1,"x":"🇦🇷 is the flag of Argentina.","about":["argentina"]},
{"id":"FL-174","lv":"ea","d":3,"area":"Oceania","q":"Whose flag is 🇦🇺?","o":["Fiji","Australia","New Zealand","Papua New Guinea"],"a":[1],"s":1,"x":"🇦🇺 is the flag of Australia.","about":["australia"]},
{"id":"FL-175","lv":"ea","d":3,"area":"Oceania","q":"Whose flag is 🇳🇿?","o":["Australia","New Zealand","Fiji","Papua New Guinea"],"a":[1],"s":1,"x":"🇳🇿 is the flag of New Zealand.","about":["new-zealand"]},
{"id":"FL-176","lv":"mi","d":5,"area":"Oceania","q":"Whose flag is 🇵🇬?","o":["Papua New Guinea","New Zealand","Fiji","Australia"],"a":[0],"s":1,"x":"🇵🇬 is the flag of Papua New Guinea.","about":["papua-new-guinea"]},
{"id":"FL-177","lv":"ha","d":6,"area":"Oceania","q":"Whose flag is 🇫🇯?","o":["Papua New Guinea","Solomon Islands","Fiji","Vanuatu"],"a":[2],"s":1,"x":"🇫🇯 is the flag of Fiji.","about":["fiji"]},
{"id":"FL-178","lv":"ha","d":8,"area":"Oceania","q":"Whose flag is 🇼🇸?","o":["Solomon Islands","Samoa","Tonga","Vanuatu"],"a":[1],"s":1,"x":"🇼🇸 is the flag of Samoa.","about":["samoa"]},
{"id":"FL-179","lv":"ha","d":8,"area":"Oceania","q":"Whose flag is 🇹🇴?","o":["Vanuatu","Samoa","Solomon Islands","Tonga"],"a":[3],"s":1,"x":"🇹🇴 is the flag of Tonga.","about":["tonga"]},
{"id":"FL-180","lv":"ha","d":8,"area":"Oceania","q":"Whose flag is 🇻🇺?","o":["Vanuatu","Samoa","Tonga","Solomon Islands"],"a":[0],"s":1,"x":"🇻🇺 is the flag of Vanuatu.","about":["vanuatu"]},
{"id":"FL-181","lv":"ha","d":8,"area":"Oceania","q":"Whose flag is 🇸🇧?","o":["Tonga","Vanuatu","Solomon Islands","Samoa"],"a":[2],"s":1,"x":"🇸🇧 is the flag of Solomon Islands.","about":["solomon-islands"]},
{"id":"FL-182","lv":"ha","d":9,"area":"Oceania","q":"Whose flag is 🇫🇲?","o":["Marshall Islands","Micronesia","Tuvalu","Kiribati"],"a":[1],"s":1,"x":"🇫🇲 is the flag of Micronesia.","about":["micronesia"]},
{"id":"FL-183","lv":"ha","d":9,"area":"Oceania","q":"Whose flag is 🇵🇼?","o":["Micronesia","Palau","Kiribati","Marshall Islands"],"a":[1],"s":1,"x":"🇵🇼 is the flag of Palau.","about":["palau"]},
{"id":"FL-184","lv":"ha","d":9,"area":"Oceania","q":"Whose flag is 🇰🇮?","o":["Marshall Islands","Tuvalu","Kiribati","Micronesia"],"a":[2],"s":1,"x":"🇰🇮 is the flag of Kiribati.","about":["kiribati"]},
{"id":"FL-185","lv":"ha","d":9,"area":"Oceania","q":"Whose flag is 🇲🇭?","o":["Marshall Islands","Nauru","Tuvalu","Micronesia"],"a":[0],"s":1,"x":"🇲🇭 is the flag of Marshall Islands.","about":["marshall-islands"]},
{"id":"FL-186","lv":"ha","d":9,"area":"Oceania","q":"Whose flag is 🇳🇷?","o":["Palau","Nauru","Marshall Islands","Tuvalu"],"a":[1],"s":1,"x":"🇳🇷 is the flag of Nauru.","about":["nauru"]},
{"id":"FL-187","lv":"ha","d":9,"area":"Oceania","q":"Whose flag is 🇹🇻?","o":["Palau","Marshall Islands","Kiribati","Tuvalu"],"a":[3],"s":1,"x":"🇹🇻 is the flag of Tuvalu.","about":["tuvalu"]},
{"id":"FL-188","lv":"mi","d":5,"area":"Europe","q":"Whose flag is 🇻🇦?","o":["Vatican City","Albania","Slovenia","Bosnia and Herzegovina"],"a":[0],"s":1,"x":"🇻🇦 is the flag of Vatican City.","about":["vatican-city"]},
{"id":"FL-189","lv":"mi","d":5,"area":"Middle East","q":"Whose flag is 🇵🇸?","o":["Bahrain","Palestine","Oman","Yemen"],"a":[1],"s":1,"x":"🇵🇸 is the flag of Palestine.","about":["palestine"]},
{"id":"FL-190","lv":"ha","d":8,"area":"Africa","q":"Whose flag is 🇰🇲?","o":["Benin","Lesotho","São Tomé and Príncipe","Comoros"],"a":[3],"s":1,"x":"🇰🇲 is the flag of Comoros.","about":["comoros"]},
{"id":"FL-191","lv":"ha","d":8,"area":"Africa","q":"Whose flag is 🇸🇹?","o":["São Tomé and Príncipe","Equatorial Guinea","Central African Republic","Eswatini"],"a":[0],"s":1,"x":"🇸🇹 is the flag of São Tomé and Príncipe.","about":["sao-tome-and-principe"]},
{"id":"FL-192","lv":"ha","d":8,"area":"Americas","q":"Whose flag is 🇩🇲?","o":["Dominica","Belize","Grenada","Antigua and Barbuda"],"a":[0],"s":1,"x":"🇩🇲 is the flag of Dominica.","about":["dominica"]},
{"id":"FL-193","lv":"ha","d":8,"area":"Americas","q":"Whose flag is 🇬🇩?","o":["Saint Lucia","Dominica","Grenada","Antigua and Barbuda"],"a":[2],"s":1,"x":"🇬🇩 is the flag of Grenada.","about":["grenada"]},
{"id":"FL-194","lv":"ha","d":8,"area":"Americas","q":"Whose flag is 🇱🇨?","o":["Saint Lucia","Grenada","Dominica","Belize"],"a":[0],"s":1,"x":"🇱🇨 is the flag of Saint Lucia.","about":["saint-lucia"]},
{"id":"FL-195","lv":"ha","d":9,"area":"Americas","q":"Whose flag is 🇰🇳?","o":["Saint Vincent and the Grenadines","Antigua and Barbuda","Grenada","Saint Kitts and Nevis"],"a":[3],"s":1,"x":"🇰🇳 is the flag of Saint Kitts and Nevis.","about":["saint-kitts-and-nevis"]},
{"id":"FL-196","lv":"ha","d":9,"area":"Americas","q":"Whose flag is 🇻🇨?","o":["Antigua and Barbuda","Dominica","Saint Vincent and the Grenadines","Saint Kitts and Nevis"],"a":[2],"s":1,"x":"🇻🇨 is the flag of Saint Vincent and the Grenadines.","about":["saint-vincent-and-the-grenadines"]},
{"id":"FL-197","lv":"ha","d":8,"area":"Americas","q":"Whose flag is 🇦🇬?","o":["Saint Lucia","Antigua and Barbuda","Belize","Dominica"],"a":[1],"s":1,"x":"🇦🇬 is the flag of Antigua and Barbuda.","about":["antigua-and-barbuda"]}
];
