// Punt's skiing questions (skiing-bank.js is written from this; the build adds the resorts', ski areas', races' and skiers'
// own questions from kb/entities.js). d: difficulty on Punt's scale of 1 to 10.
export const STAGES = [{"id":"resorts","label":"Resorts"},{"id":"areas","label":"Ski areas"},{"id":"races","label":"Races and runs"},{"id":"skiers","label":"Great skiers"},{"id":"history","label":"History"},{"id":"technique","label":"Technique and rules"},{"id":"safety","label":"Avalanches"},{"id":"business","label":"Passes, food and races"}];
export const ITEMS = [
{"id":"SK-H01","lv":"history","d":3,"area":"History","q":"Winter tourism in the Alps began in 1864 when Johannes Badrutt","o":["bet his English summer guests they'd love a winter stay","built the first funicular up to Corviglia","opened the first ski school in St. Moritz","persuaded the Olympics to come to St. Moritz"],"a":[0],"s":1,"x":"If they didn't enjoy it, he'd pay their travel; they stayed until Easter.","about":["johannes-badrutt"]},
{"id":"SK-H02","lv":"history","d":4,"area":"History","q":"Sondre Norheim, the father of modern skiing, came from","o":["the Arlberg, in Austria","Lapland, in Sweden","Telemark, in Norway","Chamonix, in France"],"a":[2],"s":1,"x":"His stiff heel bindings made turning and jumping possible; the Telemark and Christiania turns are named after Norwegian places.","about":["sondre-norheim"]},
{"id":"SK-H03","lv":"history","d":3,"area":"History","q":"The slalom was invented in 1922 at Mürren by","o":["Hannes Schneider, an Austrian","Mathias Zdarsky, a Moravian","Arnold Lunn, an Englishman","Sondre Norheim, a Norwegian"],"a":[2],"s":1,"x":"Lunn also founded the Kandahar Ski Club; Schneider taught the Arlberg technique, and Zdarsky wrote the first Alpine method.","about":["arnold-lunn"]},
{"id":"SK-H04","lv":"history","d":4,"area":"History","q":"The first chairlift, at Sun Valley in 1936, was adapted from","o":["machinery for loading bananas onto ships","a conveyor for coal in Pennsylvania","a cable car built for the Swiss army","a ski tow made from a car engine"],"a":[0],"s":1,"x":"A Union Pacific engineer, James Curran, swapped the banana hooks for chairs."},
{"id":"SK-H05","lv":"history","d":5,"area":"History","q":"Jan Boklöv's V-style jump, first scorned and marked down for style,","o":["was banned after a series of crashes","is used only on the largest ski-flying hills","was invented to cut the wind at take-off","flies farther, and is used by every jumper now"],"a":[3],"s":1,"x":"Spreading the skis turns the body into a wing; by the 1990s everyone jumped that way.","about":["jan-boklov"]},
{"id":"SK-H06","lv":"history","d":4,"area":"History","q":"The first Winter Olympics, at Chamonix in 1924, had no","o":["ski jumping","ice hockey","alpine skiing","bobsleigh"],"a":[2],"s":1,"x":"Alpine events joined in 1936 at Garmisch; jumping, hockey and the bobsleigh were there in 1924."},
{"id":"SK-T01","lv":"technique","d":3,"area":"Technique and rules","q":"Carving skis, from the 1990s, turn more easily because","o":["they're shorter, so they spin on the spot","they're waisted, so a tilted ski bends into an arc","their bases are grooved like a skate","their edges are rounded off for grip"],"a":[1],"s":1,"x":"The deeper the sidecut, the tighter the turn the ski carves when edged."},
{"id":"SK-T02","lv":"technique","d":4,"area":"Technique and rules","q":"A binding's DIN setting decides","o":["how hard a fall has to be before the boot releases","how far forward the boot sits on the ski","how much the boot can flex forward","how fast the ski can be sold abroad"],"a":[0],"s":1,"x":"Set by weight, height, boot length, age and skill; too low and you come out, too high and you don't."},
{"id":"SK-T03","lv":"technique","d":2,"area":"Technique and rules","q":"On European pistes, the hardest are marked","o":["red","black","double black diamond","orange"],"a":[1],"s":1,"x":"Blue, red and black (with green for beginners in France and some others); North America uses a green circle, blue square, black diamond and double black diamond."},
{"id":"SK-T04","lv":"technique","d":3,"area":"Technique and rules","q":"Under the FIS rules of conduct, right of way belongs to","o":["the skier coming from the right","the skier below you","the faster skier","whoever shouts first"],"a":[1],"s":1,"x":"The skier above must choose a line that doesn't endanger those below."},
{"id":"SK-S01","lv":"safety","d":4,"area":"Avalanches","q":"Most avalanche deaths happen when the danger is rated","o":["5, 'very high', of 5","4, 'high', of 5","1, 'low', of 5","3, 'considerable', of 5"],"a":[3],"s":1,"x":"At 'considerable', many go out who would stay in at 'high', and slabs can still be set off by one skier."},
{"id":"SK-S02","lv":"safety","d":5,"area":"Avalanches","q":"Avalanche transceivers all transmit on","o":["27 MHz","457 kHz","2.4 GHz","121.5 MHz"],"a":[1],"s":1,"x":"The worldwide standard; 121.5 MHz is the aviation emergency frequency."},
{"id":"SK-S03","lv":"safety","d":4,"area":"Avalanches","q":"Most avalanche victims are caught in","o":["powder avalanches from far above","slab avalanches they set off themselves","wet slides in spring sunshine","cornices collapsing on ridges"],"a":[1],"s":1,"x":"A cohesive slab breaks away on a weak layer, often triggered by the victim's own weight."},
{"id":"SK-B01","lv":"business","d":4,"area":"Passes, food and races","q":"The 'pass wars' are between","o":["the Swiss and Austrian national passes","the Dolomiti Superski and the Ski Arlberg pass","the 3 Vallées and the Portes du Soleil","Vail Resorts' Epic Pass and Alterra's Ikon Pass"],"a":[3],"s":1,"x":"Season passes covering dozens of resorts, sold cheap in spring; Vail has also bought Andermatt and Crans-Montana.","about":["epic-pass"]},
{"id":"SK-B02","lv":"business","d":3,"area":"Passes, food and races","q":"Raclette takes its name from","o":["a village in the Valais","the dairyman who first melted it","the iron pan it was baked in","the French 'racler', to scrape"],"a":[3],"s":1,"x":"Half a wheel is heated and the melted cheese scraped onto potatoes.","about":["raclette"]},
{"id":"SK-B03","lv":"business","d":4,"area":"Passes, food and races","q":"The Patrouille des Glaciers is","o":["the avalanche patrol that guards the Matterhorn's slopes","a glacier tour from Saas-Fee to Grindelwald","the Swiss national team's summer training camp","the Swiss army's ski-mountaineering race from Zermatt to Verbier"],"a":[3],"s":1,"x":"Teams of three, roped together, over some 57 km and nearly 4,000 metres of climbing, every second year.","about":["patrouille-des-glaciers"]},
{"id":"SK-B04","lv":"business","d":5,"area":"Passes, food and races","q":"St. Moritz has hosted the Winter Olympics","o":["once, in 1928","three times","never: it lost to Davos","twice, in 1928 and 1948"],"a":[3],"s":1,"x":"Lake Placid (1932, 1980) and Innsbruck (1964, 1976) have too, and Cortina (1956, and 2026 with Milan).","about":["st-moritz"]},
{"id":"SK-B05","lv":"business","d":3,"area":"Passes, food and races","q":"The Cresta Run in St. Moritz is","o":["the oldest bobsleigh run in the world","a cross-country course across the frozen lake","a natural ice track, ridden head first on a skeleton","the steepest black piste in Switzerland"],"a":[2],"s":1,"x":"Built in 1884–85; women were barred from 1929 until 2018.","about":["cresta-run"]}
];
