// Punt's watch questions (watches-bank.js is written from this; the build adds the manufactures', complications', parts' and
// finishes' own questions from kb/entities.js). d: difficulty on Punt's scale of 1 to 10. pic: a Wikipedia page whose lead
// image shows the thing; every question can be answered without it.
export const STAGES = [{"id":"makers","label":"The manufactures"},{"id":"complications","label":"Complications"},{"id":"movement","label":"Inside the movement"},{"id":"finishes","label":"Finishes"},{"id":"history","label":"History"},{"id":"icons","label":"The icons"},{"id":"seals","label":"Seals and standards"}];
export const ITEMS = [
{"id":"WT-H01","lv":"history","d":4,"area":"History","q":"Christiaan Huygens's gift to the watch, in 1675, was","o":["the fusee, which evened out the mainspring","the lever escapement, still in every watch","the first watch worn on a wrist","the balance spring, which made watches accurate"],"a":[3],"s":1,"x":"Before it, a watch might lose an hour a day. The fusee is two centuries older; the lever escapement was Thomas Mudge's.","pic":"Balance spring","about":["christiaan-huygens"]},
{"id":"WT-H02","lv":"history","d":3,"area":"History","q":"John Harrison's H4, tested at sea in 1761, solved","o":["the winding of a watch without a key","the effect of magnetism on the balance","the longitude problem, by keeping time at sea","the need for a watch to show the date"],"a":[2],"s":1,"x":"Knowing home time to the second, a navigator could work out his longitude from the sun.","pic":"Marine chronometer","about":["harrison"]},
{"id":"WT-H03","lv":"history","d":4,"area":"History","q":"Breguet patented the tourbillon in 1801 to","o":["make the first waterproof watch case","let a watch chime the hours by itself","wind a watch by the swing of walking","cancel the errors of a pocket watch hanging upright"],"a":[3],"s":1,"x":"In a wristwatch, which moves about, its benefit is debated; its beauty isn't. Breguet's self-winding 'perpétuelle' was a different invention.","pic":"Tourbillon","about":["tourbillon"]},
{"id":"WT-H04","lv":"history","d":5,"area":"History","q":"Breguet's No. 160, the 'Marie Antoinette', took","o":["one winter, as a wedding present","forty-four years, long after the queen's death","ten years, and went with her to prison","a single year, and was buried with her"],"a":[1],"s":1,"x":"Ordered in 1783 with every complication known, finished in 1827; stolen from a Jerusalem museum in 1983, recovered in 2007.","about":["abraham-louis-breguet"]},
{"id":"WT-H05","lv":"history","d":4,"area":"History","q":"The Vallée de Joux became a valley of watchmakers because","o":["Calvin banned jewellery in its little towns","its farmers made parts in the snowbound winters","its rivers drove the first watch factories","its abbey's monks taught them clockmaking"],"a":[1],"s":1,"x":"Cut off for months, families made parts and whole movements for Geneva; the valley still makes the most complicated watches."},
{"id":"WT-H06","lv":"history","d":5,"area":"History","q":"Swiss watchmaking industrialised after 1876 when, at Philadelphia's exhibition,","o":["Swiss watches won every prize for accuracy","American machine-made watches outdid Swiss handwork","the first wristwatch was put on show","a Swiss watch was given to the president"],"a":[1],"s":1,"x":"Waltham's interchangeable parts alarmed the Swiss delegates into building factories."},
{"id":"WT-H07","lv":"history","d":3,"area":"History","q":"Men took to wristwatches during","o":["the Napoleonic Wars, as cavalry watches","the Second World War, with pilots' watches","the 1890s, with the craze for bicycles","the First World War, when officers needed both hands"],"a":[3],"s":1,"x":"Before it, a wristwatch was thought a woman's thing; 'trench watches' changed that."},
{"id":"WT-H08","lv":"history","d":5,"area":"History","q":"In the quartz crisis, from the 1970s to the 1980s, Swiss watchmaking jobs fell","o":["by about a tenth","by about half","hardly at all","by about two-thirds"],"a":[3],"s":1,"x":"From about 90,000 to about 30,000; the Swatch and the mechanical revival brought the industry back.","about":["quartz-crisis"]},
{"id":"WT-H09","lv":"history","d":3,"area":"History","q":"The Swatch, in 1983, saved Swiss watchmaking with","o":["a steel sports watch priced like gold","the first automatic chronograph","a cheap plastic quartz watch with very few parts","a mechanical watch made in Japan"],"a":[2],"s":1,"x":"Just 51 parts. Nicolas Hayek merged the two failing Swiss groups into what became the Swatch Group.","about":["swatch"]},
{"id":"WT-H10","lv":"history","d":6,"area":"History","q":"A. Lange & Söhne returned in 1990 because","o":["IWC bought the name from the East German state","after reunification, Walter Lange refounded the family firm","a court gave the factory back after the war","Patek Philippe bought it from the Soviets"],"a":[1],"s":1,"x":"The East German state had taken it over in 1948; the first new watches, the Lange 1 among them, came in 1994.","about":["walter-lange"]},
{"id":"WT-I01","lv":"icons","d":2,"area":"The icons","q":"The Reverso's flipping case was made in 1931 for","o":["racing drivers at Le Mans","British officers playing polo in India","the pilots of the Swiss air force","divers of the French navy"],"a":[1],"s":1,"x":"Turned over, the steel back took the blows that broke watch glasses.","pic":"Jaeger-LeCoultre Reverso","about":["reverso"]},
{"id":"WT-I02","lv":"icons","d":3,"area":"The icons","q":"The Speedmaster went to the Moon because","o":["Omega gave one to every astronaut free","it was the only chronograph made in America","Buzz Aldrin bought his own before the flight","NASA chose it after torture-testing several makes"],"a":[3],"s":1,"x":"Heat, cold, vacuum, shock and humidity: the Speedmaster survived in 1965. On Apollo 15 Dave Scott also wore a Bulova.","pic":"Omega Speedmaster","about":["speedmaster"]},
{"id":"WT-I03","lv":"icons","d":3,"area":"The icons","q":"The Royal Oak of 1972 shocked buyers because","o":["it was a steel sports watch priced like gold","it was the first watch run by quartz","it showed the time in glowing digits","it was the first watch made of titanium"],"a":[0],"s":1,"x":"Gérald Genta is said to have drawn it overnight. The glowing digits were Hamilton's Pulsar, the same year.","about":["royal-oak"]},
{"id":"WT-I04","lv":"icons","d":3,"area":"The icons","q":"Gérald Genta designed both","o":["the Royal Oak and the Nautilus","the Reverso and the Tank","the Submariner and the Daytona","the Speedmaster and the Seamaster"],"a":[0],"s":1,"x":"And the Polerouter, the Ingenieur and the Bulgari Bulgari.","about":["gerald-genta"]},
{"id":"WT-I05","lv":"icons","d":3,"area":"The icons","q":"Cartier's Tank, of 1917, took its shape from","o":["the fuel tanks of the early aeroplanes","the new skyscrapers rising in New York","the gold ingots stored at the Paris mint","the tanks of the Western Front, seen from above"],"a":[3],"s":1,"x":"The brancards (stretchers) at the sides are the treads.","pic":"Cartier Tank","about":["tank"]},
{"id":"WT-I06","lv":"icons","d":4,"area":"The icons","q":"Paul Newman's own Rolex Daytona sold at auction in 2017 for","o":["$1.8 million","$178,000","$17.8 million","$7.8 million"],"a":[2],"s":1,"x":"A gift from his wife, Joanne Woodward, engraved 'Drive carefully me'.","pic":"Rolex Daytona","about":["daytona"]},
{"id":"WT-I07","lv":"icons","d":5,"area":"The icons","q":"Zenith's El Primero, of 1969, was one of the first","o":["quartz watches, made in Le Locle","watches to show the phase of the moon","divers' watches, tested to a thousand metres","automatic chronographs, beating ten times a second"],"a":[3],"s":1,"x":"36,000 beats an hour; in a race with Heuer and Breitling's Calibre 11 and Seiko's 6139.","about":["el-primero"]},
{"id":"WT-I08","lv":"icons","d":5,"area":"The icons","q":"The first quartz wristwatch, Seiko's Astron, went on sale","o":["in Neuchâtel, from the Swiss quartz lab, 1967","in New York, from Hamilton, 1970","in Tokyo, on Christmas Day 1969","in Biel, from Omega, 1971"],"a":[2],"s":1,"x":"The Swiss lab in Neuchâtel had shown quartz prototypes in 1967, but Seiko sold first.","about":["astron"]},
{"id":"WT-I09","lv":"icons","d":5,"area":"The icons","q":"Blancpain's Fifty Fathoms, of 1953, was made for","o":["British commandos in Norway","Italian navy frogmen","the Swiss army's mountain troops","French navy combat divers"],"a":[3],"s":1,"x":"Fifty fathoms is about 91 metres. Italy's frogmen wore Panerai.","about":["blancpain"]},
{"id":"WT-I10","lv":"icons","d":4,"area":"The icons","q":"Jaeger-LeCoultre's Memovox, of 1950, is","o":["a mechanical alarm wristwatch","a watch that speaks the time aloud","a minute repeater on a strap","a watch with a built-in compass"],"a":[0],"s":1,"x":"'The voice of memory': a hammer strikes a gong. Vulcain's Cricket, worn by Truman, came first, in 1947.","about":["memovox"]},
{"id":"WT-M01","lv":"movement","d":5,"area":"Inside the movement","q":"A movement beating 28,800 times an hour runs at","o":["two hertz: four ticks a second","four hertz: eight ticks a second","one hertz: one tick a second","ten hertz: twenty ticks a second"],"a":[1],"s":1,"x":"Each oscillation of the balance is two beats; 18,000 an hour was the old standard, 36,000 the fastest common rate."},
{"id":"WT-M02","lv":"movement","d":3,"area":"Inside the movement","q":"The jewels in a movement are","o":["diamonds set in the rotor for weight","synthetic rubies the pivots turn in","the sapphire of the crystal and back","gems added to raise the price"],"a":[1],"s":1,"x":"Seventeen make a fully jewelled lever movement; more usually means complications or an automatic.","about":["watch-jewels"]},
{"id":"WT-M03","lv":"movement","d":6,"area":"Inside the movement","q":"A movement's size is measured in lignes, an old French unit of about","o":["1 cm","1 mm","4 mm","2.26 mm"],"a":[3],"s":1,"x":"A twelfth of the French inch; an 11½-ligne movement is about 26 mm across."},
{"id":"WT-M04","lv":"movement","d":6,"area":"Inside the movement","q":"Silicon hairsprings, first used by Ulysse Nardin in 2001, are prized because","o":["magnetism doesn't touch them, and heat barely does","they cost a tenth of a steel spring","they make the watch beat twice as fast","they let the watch run for a month"],"a":[0],"s":1,"x":"Silicon is etched, not drawn, so it can take shapes steel can't."},
{"id":"WT-S01","lv":"seals","d":5,"area":"Seals and standards","q":"A COSC-certified chronometer movement must keep, each day, within","o":["−1 and +1 minute","−10 and +10 seconds","−2 and +2 seconds","−4 and +6 seconds"],"a":[3],"s":1,"x":"Over fifteen days, in five positions and at three temperatures."},
{"id":"WT-S02","lv":"seals","d":6,"area":"Seals and standards","q":"Omega's Master Chronometers must also resist","o":["magnetism as strong as an MRI scanner's","water to a thousand metres","a fall of a metre onto wood","cold of minus forty degrees"],"a":[0],"s":1,"x":"15,000 gauss, tested by METAS, the Swiss federal metrology institute, on the cased watch."},
{"id":"WT-S03","lv":"seals","d":6,"area":"Seals and standards","q":"In 2009 Patek Philippe gave up the Geneva Seal for","o":["the COSC test for chronometer movements","a seal of its own, judged on the finished watch","the Qualité Fleurier, run by four makers","the federal METAS test of the cased watch"],"a":[1],"s":1,"x":"Its own seal sets tighter accuracy than COSC for the cased watch, and rules for finish and service.","about":["patek-philippe"]},
{"id":"WT-S04","lv":"seals","d":6,"area":"Seals and standards","q":"Since 2012 the Geneva Seal has also required","o":["a case of gold or platinum, hallmarked","every single part to be made in the canton","the cased watch to keep within a minute over a week","a tourbillon or another complication"],"a":[2],"s":1,"x":"The movement must be assembled, adjusted and cased in the canton, and finished to its rules."}
];
