// The comment at the head of each bank the build writes (each describes its bank for whoever opens it).
export const HEADERS = {
 "bank.js": "// Word bank, base64-encoded JSON so answers aren't readable at a glance.\n// Append-only: board codes reference answer and word positions.",
 "chart-bank.js": "// Chart's bank: 415 places to pin on the map, each with its coordinates and a description of what it is and why it matters. Fields: id; cat\n// (cities, trade, wine, art, people, geo); name (what you're asked to pin); lat; lon; note; country and region (for the\n// clues: the country from Natural Earth's polygons, or the nearest for places at sea, corrected by hand for islands). Coordinates are to about\n// a tenth of a degree, which is finer than a thumb on a phone.",
 "chart-geo.js": "// Chart's physical features: mountain ranges, deserts, plateaus and basins, lakes (Natural Earth 10 m polygons, 50 m\n// lakes) and rivers (10 m centrelines), simplified, with a note each. A pin is scored to the nearest point of the\n// feature, and the feature is drawn at the reveal. Written notes by hand; geometry public domain (Natural Earth).",
 "quote-bank.js": "// Quote's bank: 175 numbers to make a market on, each with its truth, a scale and a note on the basis. Written\n// October 2026 and best checked against the sources; \"about\" means the figure is a rounded estimate. Fields: id;\n// cat (trade, cities, wine, art, people, geo, markets); q (the question); unit; truth; scale (\"log\": judged by\n// ratio, for magnitudes; or a number: a step, for years, percentages, counts and the like); tol: the question's own\n// range for \"close\", a ratio for magnitudes (0.15 = ±15%) and units for steps (3 = ±3 years), which sets how the\n// payout falls off; note (shown after you quote).",
 "myth-bank.js": "// Punt's mythology bank, written by tools/build-kb.mjs from kb/ (edit kb/, not this file): the gods of Greece and\n// Rome (what they ruled, their signs, their Roman names), heroes and monsters, the Norse, Egypt, and myth in words.\n// The gods' questions come from their entities; the rest are written in kb/items/choice/myth.js.\n",
 "arch-bank.js": "// Punt's architecture bank, written by tools/build-kb.mjs from kb/ (edit kb/, not this file): the styles as ideas\n// (each style's card: what it rejected, what it sought, how to spot it, what lay behind it), the buildings by sight (which\n// style, who designed it) and the parts of a building, both ways. Same shape as the maths bank.\n",
 "swiss-bank.js": "// Punt's Switzerland bank: 44 questions in three stages: Geneva (the Escalade, Calvin, the Red Cross, international\n// Geneva, watchmaking, banks and trading), the Swiss state (the Federal Council, direct democracy, neutrality, history),\n// Swiss life and money (languages, tunnels, Swiss made, chocolate, banking secrecy, the franc). Written October 2026.\n// Same shape as the maths bank. Written by tools/build-kb.mjs from kb/: edit kb/, not this file.\n",
 "art-bank.js": "// Punt's art bank: 225 questions. Paintings shown as pictures (pic: the English Wikipedia page title, fetched\n// at display time): who painted it, where it hangs, which movement; and stories of the art world without pictures.\n// Same shape as the maths bank, plus pic. Written by hand.",
 "cities-bank.js": "// Punt's cities bank: 506 questions. Every capital, which country a notable city is in, and what a city is known for\n// (ports, refineries, exchanges, companies, culture), with the weight on Germany, the UK, China, the rest of Europe\n// and Latin America. Same shape as the maths bank; stages by region.",
 "flags-bank.js": "// Punt's flags bank: 197 countries, the flag as its emoji (every phone draws them), distractors from the same\n// region at a similar obscurity. Same shape as the maths bank; stages by how well known the country is.",
 "eco-bank.js": "// Punt's economics bank: 73 questions in 4 units, with explanations; maths between $…$ renders as\n// LaTeX, svg carries a drawn chart, code a snippet to read. Same shape as the maths bank. Written by hand.",
 "phy-bank.js": "// Punt's physics bank: 62 questions in 4 units, with explanations; maths between $…$ renders as\n// LaTeX, svg carries a drawn chart, code a snippet to read. Same shape as the maths bank. Written by hand.",
 "chm-bank.js": "// Punt's chemistry bank: 58 questions in 4 units, with explanations; maths between $…$ renders as\n// LaTeX, svg carries a drawn chart, code a snippet to read. Same shape as the maths bank. Written by hand.",
 "cs-bank.js": "// Punt's code bank: 68 questions in 4 units, with explanations; maths between $…$ renders as\n// LaTeX, svg carries a drawn chart, code a snippet to read. Same shape as the maths bank. Written by hand.",
 "phil-bank.js": "// Punt's philosophy bank: 60 questions in 4 units, with explanations; maths between $…$ renders as\n// LaTeX, svg carries a drawn chart, code a snippet to read. Same shape as the maths bank. Written by hand.",
 "rel-bank.js": "// Punt's religion bank: 59 questions in 4 units, with explanations; maths between $…$ renders as\n// LaTeX, svg carries a drawn chart, code a snippet to read. Same shape as the maths bank. Written by hand.",
 "refining-bank.js": "// Punt's refining bank: 139 multiple-choice questions on how a refinery works, with the same shape as the maths\n// bank. Fields: id; lv (stage: bs = basics, un = units, sp = specs, gb = gasoline blending chemistry, db = diesel\n// blending chemistry, rn = renewables, ec = economics);\n// d (difficulty 1–10); area; q; o (four options); a (the right options' indices); s (how many to pick); x (the\n// explanation). Written October 2026, textbook-typical."
};
