// Writes sw.js: the service worker (tools/service-worker.js) after the list of every file the app needs offline
// (tools/offline.mjs), each with a hash of its bytes, and a version that changes whenever any of them does (so
// devices fetch what changed). The workflow (.github/workflows/pages.yml) runs it after every game's tests pass and
// commits the result; nothing else writes sw.js, so nobody collides on it. Locally it writes only with --local (to
// try offline play: don't commit it); --check only reports.  node tools/build-sw.mjs [--check | --local]
import fs from "fs";
import crypto from "crypto";
import { ROOT, offlineFiles } from "./offline.mjs";

/** The first 12 hex digits of the SHA-1 of some bytes: the service worker hashes what it holds the same way. */
export const hashOf = bytes => crypto.createHash("sha1").update(bytes).digest("hex").slice(0, 12);

/** sw.js's text for the files as they are now. */
export function serviceWorker(root = ROOT) {
  const files = offlineFiles(root), logic = fs.readFileSync(new URL("./service-worker.js", import.meta.url), "utf8");
  const hashes = { "./": hashOf(fs.readFileSync(root + "index.html")) };   // the app's own address is the games screen
  for (const f of files) hashes[f] = hashOf(fs.readFileSync(root + f));
  const version = hashOf(JSON.stringify([hashes, logic]));
  return { files, version, text: `// Generated by tools/build-sw.mjs: don't edit by hand.
const VERSION = "${version}";
const FILES = ${JSON.stringify(hashes, null, 2)};

${logic}` };
}

if (process.argv[1] === new URL(import.meta.url).pathname) {
  const { files, version, text } = serviceWorker();
  const current = fs.existsSync(ROOT + "sw.js") ? fs.readFileSync(ROOT + "sw.js", "utf8") : "";
  if (process.argv.includes("--check")) {
    console.log(current === text ? `sw.js is current (${files.length} files, version ${version})` : "sw.js is out of date: the workflow publishes it once every test passes");
    if (current !== text) process.exitCode = 1;
  } else if (process.env.GITHUB_ACTIONS === "true" || process.argv.includes("--local")) {
    fs.writeFileSync(ROOT + "sw.js", text);
    console.log(`sw.js: ${files.length} files, version ${version}`);
  } else {
    console.log("sw.js is published by the workflow once every test passes: nothing written (--local writes one to try offline play; don't commit it).");
  }
}
