// Writes sw.js: the list of every file the games need offline, and a version that changes whenever any of them
// does (so devices fetch the new set). The workflow (.github/workflows/pages.yml) runs it after every game's tests
// pass and commits the result; nothing else writes sw.js, so nobody collides on it. Locally it writes only with
// --local (to try offline play: don't commit it); --check only reports.  node tools/build-sw.mjs [--check | --local]
import fs from "fs";
import crypto from "crypto";
import { execSync } from "child_process";

const root = new URL("..", import.meta.url).pathname;
const SHIP = /\.(html|js|css|webmanifest|woff2|png|svg)$/;
const files = execSync("git ls-files", { cwd: root, encoding: "utf8" }).split("\n")
  .filter(f => SHIP.test(f) && !f.startsWith("tests/") && !f.startsWith("tools/") && !f.startsWith("kb/") && f !== "sw.js")   // kb/ is the source the banks are built from
  .concat(fs.readdirSync(root + "fonts").map(f => `fonts/${f}`), fs.readdirSync(root + "icons").map(f => `icons/${f}`))
  .filter((f, i, all) => all.indexOf(f) === i && fs.existsSync(root + f))
  .sort();
const hash = crypto.createHash("sha1");
for (const f of files) hash.update(f).update(fs.readFileSync(root + f));
const version = hash.digest("hex").slice(0, 12);

const sw = `// Generated by tools/build-sw.mjs: don't edit by hand.
// Keeps every file of every game on the device, so the games open and play offline. The version changes with
// any file, so devices fetch the new set in the background; it waits until the app is off screen to take over
// (see pwa.js). Requests to other sites (Firebase, for playing together) go straight to the network.
const VERSION = "${version}";
const CACHE = \`crates-\${VERSION}\`;
const FILES = ${JSON.stringify(["./", ...files], null, 2)};

self.addEventListener("install", event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(FILES.map(f => new Request(f, { cache: "reload" })))));
});
self.addEventListener("activate", event => {
  event.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith("crates-") && k !== CACHE && k !== PUZZLES && k !== PICS).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener("message", event => { if (event.data === "take-over") self.skipWaiting(); });
// The chess puzzle bands (puzzles/*.txt) are big and rarely change: fetched when a run needs them and kept in a
// cache of their own, which an app update leaves alone.
const PUZZLES = "crates-puzzles-1", PICS = "crates-pics-2";   // pics-2: the old one could hold refused thumbnails
self.addEventListener("fetch", event => {
  if (event.request.method === "GET" && new URL(event.request.url).pathname.includes("/puzzles/")) {
    event.respondWith(caches.open(PUZZLES).then(cache => cache.match(event.request).then(hit => hit || fetch(event.request).then(res => { if (res.ok) cache.put(event.request, res.clone()); return res; }))));
    return;
  }
  const url = new URL(event.request.url);
  // pictures from Wikipedia (the API's answers and the images themselves, thumbnails now served from
  // thumb.wikimedia.org) are kept once fetched, in a cache of their own; an image fetched by an <img> comes back
  // opaque (no CORS), which can still be kept and served back to an <img>
  const wiki = url.hostname === "en.wikipedia.org" && url.pathname === "/w/api.php" && url.searchParams.get("prop") === "pageimages";
  if (event.request.method === "GET" && (wiki || url.hostname === "upload.wikimedia.org" || url.hostname === "thumb.wikimedia.org")) {
    event.respondWith(caches.open(PICS).then(cache => cache.match(event.request).then(hit => hit || fetch(event.request).then(res => {
      if (res.ok || res.type === "opaque") cache.put(event.request, res.clone());
      return res;
    }))));
    return;
  }
  if (event.request.method !== "GET" || url.origin !== self.location.origin) return;
  event.respondWith(caches.open(CACHE)
    .then(cache => cache.match(event.request, { ignoreSearch: true }))
    .then(hit => hit || fetch(event.request)));
});
`;
const current = fs.existsSync(root + "sw.js") ? fs.readFileSync(root + "sw.js", "utf8") : "";
if (process.argv.includes("--check")) {
  console.log(current === sw ? `sw.js is current (${files.length} files, version ${version})` : "sw.js is out of date: the workflow publishes it once every test passes");
  if (current !== sw) process.exitCode = 1;
} else if (process.env.GITHUB_ACTIONS === "true" || process.argv.includes("--local")) {
  fs.writeFileSync(root + "sw.js", sw);
  console.log(`sw.js: ${files.length} files, version ${version}`);
} else {
  console.log("sw.js is published by the workflow once every test passes: nothing written (--local writes one to try offline play; don't commit it).");
}
